//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.AgencyUserApprovalStructure, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class AgencyUserApprovalStructure {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for AgencyUserApprovalStructure constructor in the schema.
        /// </summary>
        public AgencyUserApprovalStructure()
        {
            this.Idpeticionario = 0;
            this.Wein = @"N";
            this.Weinmanager = @"NULL";
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual long Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpeticionario in the schema.
        /// </summary>
        public virtual int Idpeticionario
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Wein in the schema.
        /// </summary>
        public virtual string Wein
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpeticionariomanager in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idpeticionariomanager
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Weinmanager in the schema.
        /// </summary>
        public virtual string Weinmanager
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Creationdate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Creationdate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Lastupdatedate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Lastupdatedate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Peticionarios_IdPeticionario in the schema.
        /// </summary>
        public virtual Peticionarios Peticionarios_IdPeticionario
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Peticionarios_IdPeticionarioManager in the schema.
        /// </summary>
        public virtual Peticionarios Peticionarios_IdPeticionarioManager
        {
            get;
            set;
        }
    }

}
