//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Amecs, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Amecs {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Amecs constructor in the schema.
        /// </summary>
        public Amecs()
        {
            this.Detallecriterios = @"NULL";
            this.Duracionhoras = @"NULL";
            this.Conceptogastos = @"NULL";
            this.Cargoadaxas = @"NULL";
            this.Programaamecs = @"NULL";
            this.Urlprograma = @"NULL";
            this.Descripcionobjetivo = @"NULL";
            this.Descripcion = @"NULL";
            this.Lugarsede = @"NULL";
            this.Criterioespecificado = @"NULL";
            this.Veeva = false;
            this.Newco = false;
            this.Aprobadoramecs = new HashSet<Aprobadoramec>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idamecs in the schema.
        /// </summary>
        public virtual string Idamecs
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idsolicitante in the schema.
        /// </summary>
        public virtual int Idsolicitante
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idcargo in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idcargo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idcreadopor in the schema.
        /// </summary>
        public virtual int Idcreadopor
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechaamecs in the schema.
        /// </summary>
        public virtual System.DateTime Fechaamecs
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Nwein in the schema.
        /// </summary>
        public virtual string Nwein
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipoactividad in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idtipoactividad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Preaprobadaamed in the schema.
        /// </summary>
        public virtual System.Nullable<short> Preaprobadaamed
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Preaprobadaneg in the schema.
        /// </summary>
        public virtual short Preaprobadaneg
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Preaprobadaleg in the schema.
        /// </summary>
        public virtual short Preaprobadaleg
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Farmaindustria in the schema.
        /// </summary>
        public virtual short Farmaindustria
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Casosclinicos in the schema.
        /// </summary>
        public virtual short Casosclinicos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Participantesmsd in the schema.
        /// </summary>
        public virtual System.Nullable<long> Participantesmsd
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Detallecriterios in the schema.
        /// </summary>
        public virtual string Detallecriterios
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Medicosfichero in the schema.
        /// </summary>
        public virtual System.Nullable<short> Medicosfichero
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Duracionhoras in the schema.
        /// </summary>
        public virtual string Duracionhoras
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Ponentespatrocinados in the schema.
        /// </summary>
        public virtual System.Nullable<long> Ponentespatrocinados
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Conceptogastos in the schema.
        /// </summary>
        public virtual string Conceptogastos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Cargoadaxas in the schema.
        /// </summary>
        public virtual string Cargoadaxas
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Importegasto in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> Importegasto
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Cartascontrato in the schema.
        /// </summary>
        public virtual System.Nullable<long> Cartascontrato
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Programaamecs in the schema.
        /// </summary>
        public virtual string Programaamecs
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Urlprograma in the schema.
        /// </summary>
        public virtual string Urlprograma
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Descripcionobjetivo in the schema.
        /// </summary>
        public virtual string Descripcionobjetivo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idestado in the schema.
        /// </summary>
        public virtual long Idestado
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Descripcion in the schema.
        /// </summary>
        public virtual string Descripcion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Politican20 in the schema.
        /// </summary>
        public virtual System.Nullable<short> Politican20
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechacomienzo in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Fechacomienzo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechafinalizacion in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Fechafinalizacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Lugarsede in the schema.
        /// </summary>
        public virtual string Lugarsede
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idcriterioseleccion in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idcriterioseleccion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Criterioespecificado in the schema.
        /// </summary>
        public virtual string Criterioespecificado
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idnivelaprobacion in the schema.
        /// </summary>
        public virtual System.Nullable<long> Idnivelaprobacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Paraguas in the schema.
        /// </summary>
        public virtual short Paraguas
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Importegastoacumulado in the schema.
        /// </summary>
        public virtual System.Nullable<double> Importegastoacumulado
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Profesionalessanitarios in the schema.
        /// </summary>
        public virtual System.Nullable<long> Profesionalessanitarios
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idconfempresa in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idconfempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechaultimaactualizacion in the schema.
        /// </summary>
        public virtual System.DateTime Fechaultimaactualizacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idposition in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idposition
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idamecsrelacionado in the schema.
        /// </summary>
        public virtual string Idamecsrelacionado
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Veeva in the schema.
        /// </summary>
        public virtual bool Veeva
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Newco in the schema.
        /// </summary>
        public virtual bool Newco
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Peticionarios_idsolicitante in the schema.
        /// </summary>
        public virtual Peticionarios Peticionarios_idsolicitante
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Confempresa in the schema.
        /// </summary>
        public virtual Confempresa Confempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Peticionarios_idcreadopor in the schema.
        /// </summary>
        public virtual Peticionarios Peticionarios_idcreadopor
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Nivelesaprobacion in the schema.
        /// </summary>
        public virtual Nivelesaprobacion Nivelesaprobacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Criteriosseleccion in the schema.
        /// </summary>
        public virtual Criteriosseleccion Criteriosseleccion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Aprobadoramecs in the schema.
        /// </summary>
        public virtual ISet<Aprobadoramec> Aprobadoramecs
        {
            get;
            set;
        }
    }

}
