//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Amec, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Amec {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Amec constructor in the schema.
        /// </summary>
        public Amec()
        {
            this.Idamec = 0;
            this.Idempresa = 0;
            this.Inactivo = 0;
            this.Idestado = @"N";
            this.Aprobado = 0;
            this.Aprobadolegal = 0;
            this.Aprobadocomplaice = 0;
            this.Paraguas = 0;
            this.Especificarotras = @"N";
            this.Nombreprograma = @"N";
            this.Codgenesis = @"N";
            this.Objetivosprograma = @"N";
            this.Contenido = @"N";
            this.Lugar = @"N";
            this.Ambitogeografico = @"N";
            this.Duracion = @"N";
            this.Numparticipantes = 0;
            this.GastosdesAloj = @"N";
            this.Otros = @"N";
            this.Relponentes = @"N";
            this.Numponentes = 0;
            this.Observacioneslegal = @"N";
            this.Honorarios = @"N";
            this.Conceptogastos = @"NULL";
            this.Numpropuestas = 0;
            this.Numcartas = 0;
            this.Numhojasinscripcion = 0;
            this.Mailautorizadofi = @"N";
            this.Ficheroprograma = @"N";
            this.Aprobadodg = 0;
            this.Observacionescomplaice = @"N";
            this.Observacionesdg = @"N";
            this.AmecComunicado = 0;
            this.ComunicarAmec = 0;
            this.Observaciones = @"N";
            this.Area = @"N";
            this.Numboletines = 0;
            this.Expedientes = new HashSet<Expediente>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idamec in the schema.
        /// </summary>
        public virtual int Idamec
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Amec1 in the schema.
        /// </summary>
        public virtual string Amec1
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idempresa in the schema.
        /// </summary>
        public virtual int Idempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpeticionactividad in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idpeticionactividad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idcongreso in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idcongreso
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Inactivo in the schema.
        /// </summary>
        public virtual short Inactivo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idestado in the schema.
        /// </summary>
        public virtual string Idestado
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Aprobado in the schema.
        /// </summary>
        public virtual System.Nullable<short> Aprobado
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpeticionario in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idpeticionario
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechaaprobadolegal in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Fechaaprobadolegal
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Aprobadolegal in the schema.
        /// </summary>
        public virtual System.Nullable<short> Aprobadolegal
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpeticionario2 in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idpeticionario2
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechaaprobadocomplaice in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Fechaaprobadocomplaice
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Aprobadocomplaice in the schema.
        /// </summary>
        public virtual System.Nullable<short> Aprobadocomplaice
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idarea in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idarea
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idarea1 in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idarea1
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idarea2 in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idarea2
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idarea3 in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idarea3
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idunidad in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idunidad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipoactividadcongreso in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idtipoactividadcongreso
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Iddistrito in the schema.
        /// </summary>
        public virtual System.Nullable<int> Iddistrito
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Paraguas in the schema.
        /// </summary>
        public virtual System.Nullable<short> Paraguas
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Especificarotras in the schema.
        /// </summary>
        public virtual string Especificarotras
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Nombreprograma in the schema.
        /// </summary>
        public virtual string Nombreprograma
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Codgenesis in the schema.
        /// </summary>
        public virtual string Codgenesis
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Objetivosprograma in the schema.
        /// </summary>
        public virtual string Objetivosprograma
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Contenido in the schema.
        /// </summary>
        public virtual string Contenido
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Lugar in the schema.
        /// </summary>
        public virtual string Lugar
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Ambitogeografico in the schema.
        /// </summary>
        public virtual string Ambitogeografico
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Duracion in the schema.
        /// </summary>
        public virtual string Duracion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Numparticipantes in the schema.
        /// </summary>
        public virtual System.Nullable<int> Numparticipantes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechacomienzop in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Fechacomienzop
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechafinp in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Fechafinp
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for GastosdesAloj in the schema.
        /// </summary>
        public virtual string GastosdesAloj
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idcriterio in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idcriterio
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idcriterio2 in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idcriterio2
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idcriterio3 in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idcriterio3
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Otros in the schema.
        /// </summary>
        public virtual string Otros
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Relponentes in the schema.
        /// </summary>
        public virtual string Relponentes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Numponentes in the schema.
        /// </summary>
        public virtual System.Nullable<int> Numponentes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Observacioneslegal in the schema.
        /// </summary>
        public virtual string Observacioneslegal
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Honorarios in the schema.
        /// </summary>
        public virtual string Honorarios
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Conceptogastos in the schema.
        /// </summary>
        public virtual string Conceptogastos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Importetotal in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> Importetotal
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Numpropuestas in the schema.
        /// </summary>
        public virtual System.Nullable<int> Numpropuestas
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Numcartas in the schema.
        /// </summary>
        public virtual System.Nullable<int> Numcartas
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Numhojasinscripcion in the schema.
        /// </summary>
        public virtual System.Nullable<int> Numhojasinscripcion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipopatrocinio in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idtipopatrocinio
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Mailautorizadofi in the schema.
        /// </summary>
        public virtual string Mailautorizadofi
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Ficheroprograma in the schema.
        /// </summary>
        public virtual string Ficheroprograma
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechaaprobadodg in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Fechaaprobadodg
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Aprobadodg in the schema.
        /// </summary>
        public virtual System.Nullable<short> Aprobadodg
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Observacionescomplaice in the schema.
        /// </summary>
        public virtual string Observacionescomplaice
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Observacionesdg in the schema.
        /// </summary>
        public virtual string Observacionesdg
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fecha in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Fecha
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpeticionario3 in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idpeticionario3
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AmecComunicado in the schema.
        /// </summary>
        public virtual System.Nullable<short> AmecComunicado
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ComunicarAmec in the schema.
        /// </summary>
        public virtual System.Nullable<short> ComunicarAmec
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Observaciones in the schema.
        /// </summary>
        public virtual string Observaciones
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idregion in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idregion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Area in the schema.
        /// </summary>
        public virtual string Area
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Numboletines in the schema.
        /// </summary>
        public virtual System.Nullable<int> Numboletines
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Previsioninicial in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> Previsioninicial
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdpeticionarioResponsable in the schema.
        /// </summary>
        public virtual System.Nullable<int> IdpeticionarioResponsable
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idconfempresa in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idconfempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idamecorigin in the schema.
        /// </summary>
        public virtual string Idamecorigin
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Newco in the schema.
        /// </summary>
        public virtual bool Newco
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Congresos in the schema.
        /// </summary>
        public virtual Congresos Congresos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Confempresa in the schema.
        /// </summary>
        public virtual Confempresa Confempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PeticionesActividad in the schema.
        /// </summary>
        public virtual PeticionesActividad PeticionesActividad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Expedientes in the schema.
        /// </summary>
        public virtual ISet<Expediente> Expedientes
        {
            get;
            set;
        }
    }

}
