//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Aprobadoramec, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Aprobadoramec {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Aprobadoramec constructor in the schema.
        /// </summary>
        public Aprobadoramec()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idaprovadoramec in the schema.
        /// </summary>
        public virtual int Idaprovadoramec
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idamecs in the schema.
        /// </summary>
        public virtual string Idamecs
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idaprobador in the schema.
        /// </summary>
        public virtual int Idaprobador
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idcreadopor in the schema.
        /// </summary>
        public virtual int Idcreadopor
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechacreacion in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Fechacreacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Aprobacionjefe in the schema.
        /// </summary>
        public virtual System.Nullable<int> Aprobacionjefe
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Amecs in the schema.
        /// </summary>
        public virtual Amecs Amecs
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Peticionarios_idaprobador in the schema.
        /// </summary>
        public virtual Peticionarios Peticionarios_idaprobador
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Peticionarios_idcreadopor in the schema.
        /// </summary>
        public virtual Peticionarios Peticionarios_idcreadopor
        {
            get;
            set;
        }
    }

}
