//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 09/02/2017 13:43:05
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.CalcCountryCorrespondencias, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class CalcCountryCorrespondencias {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for CalcCountryCorrespondencias constructor in the schema.
        /// </summary>
        public CalcCountryCorrespondencias()
        {
            this.Tabletext = @"N";
            this.Idstandarvalueappend = @"N";
            this.Idmaxvalueappend = @"N";
            this.Aditionalappend = @"N";
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtype in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idtype
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idglobaltype in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idglobaltype
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idnumspeakstype in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idnumspeakstype
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idcitiestype in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idcitiestype
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idnumspeaksmoderatorstype in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idnumspeaksmoderatorstype
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tabletext in the schema.
        /// </summary>
        public virtual string Tabletext
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idstandarvalue in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idstandarvalue
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idstandarvalueappend in the schema.
        /// </summary>
        public virtual string Idstandarvalueappend
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idmaxvalue in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idmaxvalue
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idmaxvalueappend in the schema.
        /// </summary>
        public virtual string Idmaxvalueappend
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Iddaysnospeak in the schema.
        /// </summary>
        public virtual System.Nullable<int> Iddaysnospeak
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Aditional in the schema.
        /// </summary>
        public virtual System.Nullable<int> Aditional
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Aditionalappend in the schema.
        /// </summary>
        public virtual string Aditionalappend
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CalcCountryCitiesType in the schema.
        /// </summary>
        public virtual CalcCountryCitiesType CalcCountryCitiesType
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CalcCountryGlobalType in the schema.
        /// </summary>
        public virtual CalcCountryGlobalType CalcCountryGlobalType
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CalcCountryNumSpeaksModeratorsType in the schema.
        /// </summary>
        public virtual CalcCountryNumSpeaksModeratorsType CalcCountryNumSpeaksModeratorsType
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CalcCountryNumSpeaksType in the schema.
        /// </summary>
        public virtual CalcCountryNumSpeaksType CalcCountryNumSpeaksType
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CalcCountryType in the schema.
        /// </summary>
        public virtual CalcCountryType CalcCountryType
        {
            get;
            set;
        }
    }

}
