//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 09/02/2017 13:43:05
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.CalcTipoReunion, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class CalcTipoReunion {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for CalcTipoReunion constructor in the schema.
        /// </summary>
        public CalcTipoReunion()
        {
            this.Tipo = @"N";
            this.CalcCorrespondencias = new HashSet<CalcCorrespondencias>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tipo in the schema.
        /// </summary>
        public virtual string Tipo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CalcCorrespondencias in the schema.
        /// </summary>
        public virtual ISet<CalcCorrespondencias> CalcCorrespondencias
        {
            get;
            set;
        }
    }

}
