//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 09/02/2017 13:43:05
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.CalcCorrespondencias, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class CalcCorrespondencias {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for CalcCorrespondencias constructor in the schema.
        /// </summary>
        public CalcCorrespondencias()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipoasistente in the schema.
        /// </summary>
        public virtual System.Nullable<long> Idtipoasistente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtiporeunion in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idtiporeunion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipopsponentes in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idtipopsponentes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtiponacionallocal in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idtiponacionallocal
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idduracionactividadponentes in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idduracionactividadponentes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtiempopreparacionponentes in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idtiempopreparacionponentes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipopsabeif in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idtipopsabeif
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idduracionactividadabeif in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idduracionactividadabeif
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtiempopreparacionabeif in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idtiempopreparacionabeif
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Ponenciacentrosalud in the schema.
        /// </summary>
        public virtual bool Ponenciacentrosalud
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tallerocurso in the schema.
        /// </summary>
        public virtual bool Tallerocurso
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Videoconferenciarepetida in the schema.
        /// </summary>
        public virtual bool Videoconferenciarepetida
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipocontratoconsultoria in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idtipocontratoconsultoria
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idcalchonorariosmaximos in the schema.
        /// </summary>
        public virtual int Idcalchonorariosmaximos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CalcAbEifNivelPs in the schema.
        /// </summary>
        public virtual CalcAbEifNivelPs CalcAbEifNivelPs
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CalcAbEifPreparacion in the schema.
        /// </summary>
        public virtual CalcAbEifPreparacion CalcAbEifPreparacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CalcHonorariosMaximos in the schema.
        /// </summary>
        public virtual CalcHonorariosMaximos CalcHonorariosMaximos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CalcPonentesDuracionActividad in the schema.
        /// </summary>
        public virtual CalcPonentesDuracionActividad CalcPonentesDuracionActividad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CalcPonentesPreparacion in the schema.
        /// </summary>
        public virtual CalcPonentesPreparacion CalcPonentesPreparacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CalcTipoContratoConsultoria in the schema.
        /// </summary>
        public virtual CalcTipoContratoConsultoria CalcTipoContratoConsultoria
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CalcPonentesNivelPs in the schema.
        /// </summary>
        public virtual CalcPonentesNivelPs CalcPonentesNivelPs
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CalcTipoReunion in the schema.
        /// </summary>
        public virtual CalcTipoReunion CalcTipoReunion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AbEifDuracionActividad in the schema.
        /// </summary>
        public virtual AbEifDuracionActividad AbEifDuracionActividad
        {
            get;
            set;
        }
    }

}
