//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 09/02/2017 13:43:05
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.CalcHonorariosMaximos, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class CalcHonorariosMaximos {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for CalcHonorariosMaximos constructor in the schema.
        /// </summary>
        public CalcHonorariosMaximos()
        {
            this.Colspan = @"N'1";
            this.Text = @"N";
            this.Value = @"N";
            this.Value2 = @"N";
            this.CalcCorrespondencias = new HashSet<CalcCorrespondencias>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FechaInicioVigencia in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> FechaInicioVigencia
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FechaFinVigencia in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> FechaFinVigencia
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Colspan in the schema.
        /// </summary>
        public virtual string Colspan
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Text in the schema.
        /// </summary>
        public virtual string Text
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Value in the schema.
        /// </summary>
        public virtual string Value
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Value2 in the schema.
        /// </summary>
        public virtual string Value2
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Floatminvalue in the schema.
        /// </summary>
        public virtual System.Nullable<float> Floatminvalue
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Specialcase in the schema.
        /// </summary>
        public virtual bool Specialcase
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Visible in the schema.
        /// </summary>
        public virtual bool Visible
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CalcCorrespondencias in the schema.
        /// </summary>
        public virtual ISet<CalcCorrespondencias> CalcCorrespondencias
        {
            get;
            set;
        }
    }

}
