//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Confempresa, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Confempresa {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Confempresa constructor in the schema.
        /// </summary>
        public Confempresa()
        {
            this.Idconfempresa = 0;
            this.Codpostal = @"N";
            this.Direccion = @"N";
            this.Linkhorariosservicios = @"N";
            this.Logoinferiorpantalla = @"N";
            this.Locked = 0;
            this.Mailtorespuesta = @"N";
            this.Formatoprgmailcomunicfi = @"N";
            this.Asuntomailcomunicfi = @"N";
            this.Mailcccomunicfi = @"N";
            this.Mailtocomunicfi = @"N";
            this.Mailfromcomunicfi = @"N";
            this.Gestordearchivo = @"N";
            this.Poblacion = @"N";
            this.Idempresa = 0;
            this.Logosuperiorpantalla = @"N";
            this.CodigoAgencia = @"N";
            this.Nombrecontacto = @"NULL";
            this.Nombreagencia = @"NULL";
            this.Mailcontacto = @"NULL";
            this.Telefonoagencia = @"NULL";
            this.Faxagencia = @"NULL";
            this.Rutaformulariogrupos = @"N";
            this.Inactive = 0;
            this.Amecs = new HashSet<Amec>();
            this.Amecs1 = new HashSet<Amecs>();
            this.Gestorinvitados = new HashSet<Gestorinvitados>();
            this.Empleadosgps = new HashSet<Empleadosgp>();
            this.QuodemAuditLogs = new HashSet<QuodemAuditLog>();
            this.Congresos = new HashSet<Congresos>();
            this.Serviciosreservasactividades = new HashSet<Serviciosreservasactividades>();
            this.Serviciosreservashotels = new HashSet<Serviciosreservashotel>();
            this.Serviciosreservasinscripciones = new HashSet<Serviciosreservasinscripciones>();
            this.Serviciosreservastransportes = new HashSet<Serviciosreservastransporte>();
            this.QuodemQueryLogs = new HashSet<QuodemQueryLog>();
            this.PeticionesActividads = new HashSet<PeticionesActividad>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idconfempresa in the schema.
        /// </summary>
        public virtual int Idconfempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Codpostal in the schema.
        /// </summary>
        public virtual string Codpostal
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Direccion in the schema.
        /// </summary>
        public virtual string Direccion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Linkhorariosservicios in the schema.
        /// </summary>
        public virtual string Linkhorariosservicios
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Logoinferiorpantalla in the schema.
        /// </summary>
        public virtual string Logoinferiorpantalla
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Mailtorespuesta in the schema.
        /// </summary>
        public virtual string Mailtorespuesta
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Formatoprgmailcomunicfi in the schema.
        /// </summary>
        public virtual string Formatoprgmailcomunicfi
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Cuerpomailcomunicfi in the schema.
        /// </summary>
        public virtual string Cuerpomailcomunicfi
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Asuntomailcomunicfi in the schema.
        /// </summary>
        public virtual string Asuntomailcomunicfi
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Mailcccomunicfi in the schema.
        /// </summary>
        public virtual string Mailcccomunicfi
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Mailtocomunicfi in the schema.
        /// </summary>
        public virtual string Mailtocomunicfi
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Mailfromcomunicfi in the schema.
        /// </summary>
        public virtual string Mailfromcomunicfi
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Gestordearchivo in the schema.
        /// </summary>
        public virtual string Gestordearchivo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Poblacion in the schema.
        /// </summary>
        public virtual string Poblacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idempresa in the schema.
        /// </summary>
        public virtual int Idempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Logosuperiorpantalla in the schema.
        /// </summary>
        public virtual string Logosuperiorpantalla
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CodigoAgencia in the schema.
        /// </summary>
        public virtual string CodigoAgencia
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Nombrecontacto in the schema.
        /// </summary>
        public virtual string Nombrecontacto
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Nombreagencia in the schema.
        /// </summary>
        public virtual string Nombreagencia
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Mailcontacto in the schema.
        /// </summary>
        public virtual string Mailcontacto
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Telefonoagencia in the schema.
        /// </summary>
        public virtual string Telefonoagencia
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Faxagencia in the schema.
        /// </summary>
        public virtual string Faxagencia
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Rutaformulariogrupos in the schema.
        /// </summary>
        public virtual string Rutaformulariogrupos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idagencia in the schema.
        /// </summary>
        public virtual string Idagencia
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Inactive in the schema.
        /// </summary>
        public virtual int Inactive
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Amecs in the schema.
        /// </summary>
        public virtual ISet<Amec> Amecs
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Amecs1 in the schema.
        /// </summary>
        public virtual ISet<Amecs> Amecs1
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Gestorinvitados in the schema.
        /// </summary>
        public virtual ISet<Gestorinvitados> Gestorinvitados
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Empleadosgps in the schema.
        /// </summary>
        public virtual ISet<Empleadosgp> Empleadosgps
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for QuodemAuditLogs in the schema.
        /// </summary>
        public virtual ISet<QuodemAuditLog> QuodemAuditLogs
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Congresos in the schema.
        /// </summary>
        public virtual ISet<Congresos> Congresos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Serviciosreservasactividades in the schema.
        /// </summary>
        public virtual ISet<Serviciosreservasactividades> Serviciosreservasactividades
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Serviciosreservashotels in the schema.
        /// </summary>
        public virtual ISet<Serviciosreservashotel> Serviciosreservashotels
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Serviciosreservasinscripciones in the schema.
        /// </summary>
        public virtual ISet<Serviciosreservasinscripciones> Serviciosreservasinscripciones
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Serviciosreservastransportes in the schema.
        /// </summary>
        public virtual ISet<Serviciosreservastransporte> Serviciosreservastransportes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for QuodemQueryLogs in the schema.
        /// </summary>
        public virtual ISet<QuodemQueryLog> QuodemQueryLogs
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PeticionesActividads in the schema.
        /// </summary>
        public virtual ISet<PeticionesActividad> PeticionesActividads
        {
            get;
            set;
        }
    }

}
