//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Congresos, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Congresos {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Congresos constructor in the schema.
        /// </summary>
        public Congresos()
        {
            this.Idcongreso = 0;
            this.Congreso = @"N";
            this.Idpoblacion = 0;
            this.Codinterno = @"N";
            this.Urlcongreso = @"N";
            this.Telemergencias = @"N";
            this.FarmaindustriaValoracion = @"N";
            this.Locked = 0;
            this.Internacional = 0;
            this.Emailsecretaria = @"N";
            this.Comunicar = 0;
            this.Publicar = 1;
            this.Autorizadomsdi = 0;
            this.Amecs = new HashSet<Amec>();
            this.Gestorinvitados = new HashSet<Gestorinvitados>();
            this.Tarifasactividads = new HashSet<Tarifasactividad>();
            this.Tarifasalojs = new HashSet<Tarifasaloj>();
            this.Tarifasinscripcions = new HashSet<Tarifasinscripcion>();
            this.PeticionesActividads = new HashSet<PeticionesActividad>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idcongreso in the schema.
        /// </summary>
        public virtual int Idcongreso
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Congreso in the schema.
        /// </summary>
        public virtual string Congreso
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipocongreso in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idtipocongreso
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpoblacion in the schema.
        /// </summary>
        public virtual int Idpoblacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Desde in the schema.
        /// </summary>
        public virtual System.DateTime Desde
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Hasta in the schema.
        /// </summary>
        public virtual System.DateTime Hasta
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idempresa in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fcierre in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Fcierre
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Codinterno in the schema.
        /// </summary>
        public virtual string Codinterno
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idproveedor in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idproveedor
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idespecialidad in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idespecialidad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Urlcongreso in the schema.
        /// </summary>
        public virtual string Urlcongreso
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Telemergencias in the schema.
        /// </summary>
        public virtual string Telemergencias
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FarmaindustriaValoracion in the schema.
        /// </summary>
        public virtual string FarmaindustriaValoracion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Internacional in the schema.
        /// </summary>
        public virtual System.Nullable<short> Internacional
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Emailsecretaria in the schema.
        /// </summary>
        public virtual string Emailsecretaria
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpeticionario in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idpeticionario
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechacreacion in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Fechacreacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Comunicar in the schema.
        /// </summary>
        public virtual System.Nullable<short> Comunicar
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idvaloracionfi in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idvaloracionfi
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Publicar in the schema.
        /// </summary>
        public virtual System.Nullable<short> Publicar
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Autorizadomsdi in the schema.
        /// </summary>
        public virtual System.Nullable<short> Autorizadomsdi
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idconfempresa in the schema.
        /// </summary>
        public virtual int Idconfempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Amecs in the schema.
        /// </summary>
        public virtual ISet<Amec> Amecs
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Confempresa in the schema.
        /// </summary>
        public virtual Confempresa Confempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Peticionarios in the schema.
        /// </summary>
        public virtual Peticionarios Peticionarios
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tiposcongreso in the schema.
        /// </summary>
        public virtual Tiposcongreso Tiposcongreso
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ValoracionFi in the schema.
        /// </summary>
        public virtual ValoracionFi ValoracionFi
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Poblaciones in the schema.
        /// </summary>
        public virtual Poblaciones Poblaciones
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Proveedores in the schema.
        /// </summary>
        public virtual Proveedores Proveedores
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Especialidades in the schema.
        /// </summary>
        public virtual Especialidades Especialidades
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Gestorinvitados in the schema.
        /// </summary>
        public virtual ISet<Gestorinvitados> Gestorinvitados
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tarifasactividads in the schema.
        /// </summary>
        public virtual ISet<Tarifasactividad> Tarifasactividads
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tarifasalojs in the schema.
        /// </summary>
        public virtual ISet<Tarifasaloj> Tarifasalojs
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tarifasinscripcions in the schema.
        /// </summary>
        public virtual ISet<Tarifasinscripcion> Tarifasinscripcions
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PeticionesActividads in the schema.
        /// </summary>
        public virtual ISet<PeticionesActividad> PeticionesActividads
        {
            get;
            set;
        }
    }

}
