//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Criteriosseleccion, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Criteriosseleccion {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Criteriosseleccion constructor in the schema.
        /// </summary>
        public Criteriosseleccion()
        {
            this.Idcriterio = 0;
            this.Criterioseleccion = @"NULL";
            this.Locked = 0;
            this.Amecs = new HashSet<Amecs>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idcriterio in the schema.
        /// </summary>
        public virtual int Idcriterio
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Criterioseleccion in the schema.
        /// </summary>
        public virtual string Criterioseleccion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idcriterioabc in the schema.
        /// </summary>
        public virtual long Idcriterioabc
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Inactivo in the schema.
        /// </summary>
        public virtual short Inactivo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Amecs in the schema.
        /// </summary>
        public virtual ISet<Amecs> Amecs
        {
            get;
            set;
        }
    }

}
