//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.DatosadicionalesReservasPassenger, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class DatosadicionalesReservasPassenger {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for DatosadicionalesReservasPassenger constructor in the schema.
        /// </summary>
        public DatosadicionalesReservasPassenger()
        {
            this.Pagosociedad = @"NULL";
            this.Descripcionobjetivos = @"NULL";
            this.PonenciaCentroSalud = false;
            this.Talleres = false;
            this.VideoconferenciaRepetida = false;
            this.Justificacion = @"NULL";
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Iddatosadicionales in the schema.
        /// </summary>
        public virtual int Iddatosadicionales
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpassengerlist in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idpassengerlist
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idexpediente in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idexpediente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipoactividadpax in the schema.
        /// </summary>
        public virtual System.Nullable<long> Idtipoactividadpax
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipoasistente in the schema.
        /// </summary>
        public virtual long Idtipoasistente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idnivelriesgo in the schema.
        /// </summary>
        public virtual long Idnivelriesgo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idjustificaciones in the schema.
        /// </summary>
        public virtual System.Nullable<long> Idjustificaciones
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Honorarios in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> Honorarios
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Pagodirecto in the schema.
        /// </summary>
        public virtual System.Nullable<short> Pagodirecto
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Pagosociedad in the schema.
        /// </summary>
        public virtual string Pagosociedad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Datacreacion in the schema.
        /// </summary>
        public virtual System.DateTime Datacreacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Ficherogenesis in the schema.
        /// </summary>
        public virtual System.Nullable<short> Ficherogenesis
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Descripcionobjetivos in the schema.
        /// </summary>
        public virtual string Descripcionobjetivos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tiporeunion in the schema.
        /// </summary>
        public virtual System.Nullable<int> Tiporeunion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PonentesDuracionactividad in the schema.
        /// </summary>
        public virtual System.Nullable<int> PonentesDuracionactividad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PonentesPreparacion in the schema.
        /// </summary>
        public virtual System.Nullable<int> PonentesPreparacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PonentesNivelps in the schema.
        /// </summary>
        public virtual System.Nullable<int> PonentesNivelps
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PonentesHonorariosmaximos in the schema.
        /// </summary>
        public virtual System.Nullable<double> PonentesHonorariosmaximos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AbeifPreparacion in the schema.
        /// </summary>
        public virtual System.Nullable<int> AbeifPreparacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AbeifDuracionactividad in the schema.
        /// </summary>
        public virtual System.Nullable<int> AbeifDuracionactividad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AbeifNivelps in the schema.
        /// </summary>
        public virtual System.Nullable<int> AbeifNivelps
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AbeifHonorariosmaximos in the schema.
        /// </summary>
        public virtual System.Nullable<double> AbeifHonorariosmaximos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PonenciaCentroSalud in the schema.
        /// </summary>
        public virtual System.Nullable<bool> PonenciaCentroSalud
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Talleres in the schema.
        /// </summary>
        public virtual System.Nullable<bool> Talleres
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for VideoconferenciaRepetida in the schema.
        /// </summary>
        public virtual System.Nullable<bool> VideoconferenciaRepetida
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for TipoPonente in the schema.
        /// </summary>
        public virtual System.Nullable<int> TipoPonente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PonentesIdhonorariosmaximos in the schema.
        /// </summary>
        public virtual System.Nullable<int> PonentesIdhonorariosmaximos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Justificacion in the schema.
        /// </summary>
        public virtual string Justificacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipocontratoconsultoria in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idtipocontratoconsultoria
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for NumeroDiasConsultoria in the schema.
        /// </summary>
        public virtual System.Nullable<int> NumeroDiasConsultoria
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for JustificacionesDatosadicionales in the schema.
        /// </summary>
        public virtual JustificacionesDatosadicionales JustificacionesDatosadicionales
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for NivelRiesgoHcpDatosadicionales in the schema.
        /// </summary>
        public virtual NivelRiesgoHcpDatosadicionales NivelRiesgoHcpDatosadicionales
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for TipoActividadPaxDatosadicionales in the schema.
        /// </summary>
        public virtual TipoActividadPaxDatosadicionales TipoActividadPaxDatosadicionales
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for TipoAsistenteDatosadicionales in the schema.
        /// </summary>
        public virtual TipoAsistenteDatosadicionales TipoAsistenteDatosadicionales
        {
            get;
            set;
        }
    }

}
