//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Districts, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Districts {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Districts constructor in the schema.
        /// </summary>
        public Districts()
        {
            this.Idempresa = 0;
            this.District = @"N";
            this.Inactivo = 0;
            this.Expedientes = new HashSet<Expediente>();
            this.Peticionarios = new HashSet<Peticionarios>();
            this.PeticionGrupos = new HashSet<PeticionGrupos>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Iddistrict in the schema.
        /// </summary>
        public virtual int Iddistrict
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idsaleforce in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idsaleforce
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idempresa in the schema.
        /// </summary>
        public virtual int Idempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for District in the schema.
        /// </summary>
        public virtual string District
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Inactivo in the schema.
        /// </summary>
        public virtual System.Nullable<int> Inactivo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Expedientes in the schema.
        /// </summary>
        public virtual ISet<Expediente> Expedientes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Peticionarios in the schema.
        /// </summary>
        public virtual ISet<Peticionarios> Peticionarios
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PeticionGrupos in the schema.
        /// </summary>
        public virtual ISet<PeticionGrupos> PeticionGrupos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Salesforce in the schema.
        /// </summary>
        public virtual Salesforce Salesforce
        {
            get;
            set;
        }
    }

}
