//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Empleadosgp, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Empleadosgp {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Empleadosgp constructor in the schema.
        /// </summary>
        public Empleadosgp()
        {
            this.Idempleadogp = @"N";
            this.Nombre = @"N";
            this.Apellido = @"N";
            this.Email = @"N";
            this.Locked = 0;
            this.Expedientes = new HashSet<Expediente>();
            this.PeticionariosEmpleadosgps = new HashSet<PeticionariosEmpleadosgp>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idconfempresa in the schema.
        /// </summary>
        public virtual int Idconfempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idempleadogp in the schema.
        /// </summary>
        public virtual string Idempleadogp
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Nombre in the schema.
        /// </summary>
        public virtual string Nombre
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Apellido in the schema.
        /// </summary>
        public virtual string Apellido
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Email in the schema.
        /// </summary>
        public virtual string Email
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Confempresa in the schema.
        /// </summary>
        public virtual Confempresa Confempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Expedientes in the schema.
        /// </summary>
        public virtual ISet<Expediente> Expedientes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PeticionariosEmpleadosgps in the schema.
        /// </summary>
        public virtual ISet<PeticionariosEmpleadosgp> PeticionariosEmpleadosgps
        {
            get;
            set;
        }
    }

}
