//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Especialidades, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Especialidades {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Especialidades constructor in the schema.
        /// </summary>
        public Especialidades()
        {
            this.Idespecialidad = 0;
            this.Codespecialidad = @"N";
            this.Especialidad = @"N";
            this.Locked = 0;
            this.Congresos = new HashSet<Congresos>();
            this.PassengersLists = new HashSet<PassengersList>();
            this.PeticionesActividads = new HashSet<PeticionesActividad>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idespecialidad in the schema.
        /// </summary>
        public virtual int Idespecialidad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Codespecialidad in the schema.
        /// </summary>
        public virtual string Codespecialidad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Especialidad in the schema.
        /// </summary>
        public virtual string Especialidad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Congresos in the schema.
        /// </summary>
        public virtual ISet<Congresos> Congresos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PassengersLists in the schema.
        /// </summary>
        public virtual ISet<PassengersList> PassengersLists
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PeticionesActividads in the schema.
        /// </summary>
        public virtual ISet<PeticionesActividad> PeticionesActividads
        {
            get;
            set;
        }
    }

}
