//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.EstadosReservas, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class EstadosReservas {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for EstadosReservas constructor in the schema.
        /// </summary>
        public EstadosReservas()
        {
            this.Idestadoinicial = @"N";
            this.Idestadofinal = @"N";
            this.Enviado = 0;
            this.Locked = 0;
            this.Tipo = @"N";
            this.Idreserva = 0;
            this.Idexpediente = 0;
            this.WaitAck = 3;
            this.Sync = 1;
            this.TransactionKey = @"NULL";
            this.Idservicio = 0;
            this.EnviadoAgencia = 0;
            this.Idtramitacion = 0;
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idregistre in the schema.
        /// </summary>
        public virtual int Idregistre
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idestadoinicial in the schema.
        /// </summary>
        public virtual string Idestadoinicial
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idestadofinal in the schema.
        /// </summary>
        public virtual string Idestadofinal
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Enviado in the schema.
        /// </summary>
        public virtual System.Nullable<short> Enviado
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechacambioestado in the schema.
        /// </summary>
        public virtual System.DateTime Fechacambioestado
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tipo in the schema.
        /// </summary>
        public virtual string Tipo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idreserva in the schema.
        /// </summary>
        public virtual int Idreserva
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idexpediente in the schema.
        /// </summary>
        public virtual int Idexpediente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for WaitAck in the schema.
        /// </summary>
        public virtual System.Nullable<int> WaitAck
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Datasync in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Datasync
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Sync in the schema.
        /// </summary>
        public virtual int Sync
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for TransactionKey in the schema.
        /// </summary>
        public virtual string TransactionKey
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idservicio in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idservicio
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for XmlData in the schema.
        /// </summary>
        public virtual string XmlData
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EnviadoAgencia in the schema.
        /// </summary>
        public virtual System.Nullable<int> EnviadoAgencia
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtramitacion in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idtramitacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Reservasviajes in the schema.
        /// </summary>
        public virtual Reservasviajes Reservasviajes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Estadosreservas_idestadofinal in the schema.
        /// </summary>
        public virtual Estadosreservas Estadosreservas_idestadofinal
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Estadosreservas_idestadoinicial in the schema.
        /// </summary>
        public virtual Estadosreservas Estadosreservas_idestadoinicial
        {
            get;
            set;
        }
    }

}
