//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Estadosreservas, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Estadosreservas {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Estadosreservas constructor in the schema.
        /// </summary>
        public Estadosreservas()
        {
            this.Idestado = @"N";
            this.Estado = @"N";
            this.Locked = 0;
            this.Expedientes = new HashSet<Expediente>();
            this.Reservasviajes = new HashSet<Reservasviajes>();
            this.Tramitacionesserviciosreservas = new HashSet<Tramitacionesserviciosreservas>();
            this.EstadosReservas_idestadofinal = new HashSet<EstadosReservas>();
            this.EstadosReservas_idestadoinicial = new HashSet<EstadosReservas>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idestado in the schema.
        /// </summary>
        public virtual string Idestado
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Estado in the schema.
        /// </summary>
        public virtual string Estado
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Expedientes in the schema.
        /// </summary>
        public virtual ISet<Expediente> Expedientes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Reservasviajes in the schema.
        /// </summary>
        public virtual ISet<Reservasviajes> Reservasviajes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tramitacionesserviciosreservas in the schema.
        /// </summary>
        public virtual ISet<Tramitacionesserviciosreservas> Tramitacionesserviciosreservas
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EstadosReservas_idestadofinal in the schema.
        /// </summary>
        public virtual ISet<EstadosReservas> EstadosReservas_idestadofinal
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EstadosReservas_idestadoinicial in the schema.
        /// </summary>
        public virtual ISet<EstadosReservas> EstadosReservas_idestadoinicial
        {
            get;
            set;
        }
    }

}
