//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Expediente, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Expediente {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Expediente constructor in the schema.
        /// </summary>
        public Expediente()
        {
            this.Idxpediente = 0;
            this.Idregion = 0;
            this.Idamec = 0;
            this.Expediente1 = @"N";
            this.Idunidad = 0;
            this.Idarea = 0;
            this.Idpeticionario = 0;
            this.Idtiporeserva = 0;
            this.Idempresa = 0;
            this.Idestado = @"N";
            this.Iddistrito = 0;
            this.Locked = 0;
            this.Codexpediente = @"N";
            this.Urgente = 0;
            this.Importetotal = 0;
            this.Visible = 1;
            this.ReservasPassengersLists = new HashSet<ReservasPassengersList>();
            this.Reservasviajes = new HashSet<Reservasviajes>();
            this.PeticionGrupos = new HashSet<PeticionGrupos>();
            this.GestordocumentalDocumentos = new HashSet<GestordocumentalDocumento>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idxpediente in the schema.
        /// </summary>
        public virtual int Idxpediente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idregion in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idregion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idamec in the schema.
        /// </summary>
        public virtual int Idamec
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Expediente1 in the schema.
        /// </summary>
        public virtual string Expediente1
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idunidad in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idunidad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idarea in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idarea
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpeticionario in the schema.
        /// </summary>
        public virtual int Idpeticionario
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtiporeserva in the schema.
        /// </summary>
        public virtual int Idtiporeserva
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idempresa in the schema.
        /// </summary>
        public virtual int Idempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idestado in the schema.
        /// </summary>
        public virtual string Idestado
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Iddistrito in the schema.
        /// </summary>
        public virtual System.Nullable<int> Iddistrito
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechacreacion in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Fechacreacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idempleadogp in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idempleadogp
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Codexpediente in the schema.
        /// </summary>
        public virtual string Codexpediente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Urgente in the schema.
        /// </summary>
        public virtual System.Nullable<short> Urgente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Importetotal in the schema.
        /// </summary>
        public virtual System.Nullable<double> Importetotal
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Visible in the schema.
        /// </summary>
        public virtual System.Nullable<short> Visible
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Iddepartament in the schema.
        /// </summary>
        public virtual System.Nullable<int> Iddepartament
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idsaleforce in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idsaleforce
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Iddistrict in the schema.
        /// </summary>
        public virtual System.Nullable<int> Iddistrict
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tipopagofee in the schema.
        /// </summary>
        public virtual System.Nullable<int> Tipopagofee
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Amec in the schema.
        /// </summary>
        public virtual Amec Amec
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Peticionarios in the schema.
        /// </summary>
        public virtual Peticionarios Peticionarios
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Estadosreservas in the schema.
        /// </summary>
        public virtual Estadosreservas Estadosreservas
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for TiposreservasWeb in the schema.
        /// </summary>
        public virtual TiposreservasWeb TiposreservasWeb
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Empleadosgp in the schema.
        /// </summary>
        public virtual Empleadosgp Empleadosgp
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Departaments in the schema.
        /// </summary>
        public virtual Departaments Departaments
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Salesforce in the schema.
        /// </summary>
        public virtual Salesforce Salesforce
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Districts in the schema.
        /// </summary>
        public virtual Districts Districts
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ReservasPassengersLists in the schema.
        /// </summary>
        public virtual ISet<ReservasPassengersList> ReservasPassengersLists
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Reservasviajes in the schema.
        /// </summary>
        public virtual ISet<Reservasviajes> Reservasviajes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PeticionGrupos in the schema.
        /// </summary>
        public virtual ISet<PeticionGrupos> PeticionGrupos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for GestordocumentalDocumentos in the schema.
        /// </summary>
        public virtual ISet<GestordocumentalDocumento> GestordocumentalDocumentos
        {
            get;
            set;
        }
    }

}
