//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.GestordocumentalSubtipodoc, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class GestordocumentalSubtipodoc {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for GestordocumentalSubtipodoc constructor in the schema.
        /// </summary>
        public GestordocumentalSubtipodoc()
        {
            this.GestordocumentalDocumentos = new HashSet<GestordocumentalDocumento>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipodoc in the schema.
        /// </summary>
        public virtual int Idtipodoc
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Nombre in the schema.
        /// </summary>
        public virtual string Nombre
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Inactivo in the schema.
        /// </summary>
        public virtual int Inactivo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Campolibre in the schema.
        /// </summary>
        public virtual bool Campolibre
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idcategoriadocumento in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idcategoriadocumento
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for GestordocumentalDocumentos in the schema.
        /// </summary>
        public virtual ISet<GestordocumentalDocumento> GestordocumentalDocumentos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for GestordocumentalTipodoc in the schema.
        /// </summary>
        public virtual GestordocumentalTipodoc GestordocumentalTipodoc
        {
            get;
            set;
        }
    }

}
