//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.GestordocumentalDocumento, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class GestordocumentalDocumento {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for GestordocumentalDocumento constructor in the schema.
        /// </summary>
        public GestordocumentalDocumento()
        {
            this.Fechamodificacion = DateTime.Now;
            this.GestordocumentalDocumentoversions = new HashSet<GestordocumentalDocumentoversion>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idamec in the schema.
        /// </summary>
        public virtual string Idamec
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idexpediente in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idexpediente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipodoc in the schema.
        /// </summary>
        public virtual int Idtipodoc
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idsubtipodoc in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idsubtipodoc
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpeticionario in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idpeticionario
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpassengerlist in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idpassengerlist
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fecha in the schema.
        /// </summary>
        public virtual System.DateTime Fecha
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Campolibre in the schema.
        /// </summary>
        public virtual string Campolibre
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechamodificacion in the schema.
        /// </summary>
        public virtual System.DateTime Fechamodificacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Expediente in the schema.
        /// </summary>
        public virtual Expediente Expediente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PassengersList in the schema.
        /// </summary>
        public virtual PassengersList PassengersList
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Peticionarios in the schema.
        /// </summary>
        public virtual Peticionarios Peticionarios
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for GestordocumentalSubtipodoc in the schema.
        /// </summary>
        public virtual GestordocumentalSubtipodoc GestordocumentalSubtipodoc
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for GestordocumentalTipodoc in the schema.
        /// </summary>
        public virtual GestordocumentalTipodoc GestordocumentalTipodoc
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for GestordocumentalDocumentoversions in the schema.
        /// </summary>
        public virtual ISet<GestordocumentalDocumentoversion> GestordocumentalDocumentoversions
        {
            get;
            set;
        }
    }

}
