//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.GestordocumentalDocumentoversion, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class GestordocumentalDocumentoversion {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for GestordocumentalDocumentoversion constructor in the schema.
        /// </summary>
        public GestordocumentalDocumentoversion()
        {
            this.Fechamodificacion = DateTime.Now;
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Iddocumento in the schema.
        /// </summary>
        public virtual int Iddocumento
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Nombreoriginal in the schema.
        /// </summary>
        public virtual string Nombreoriginal
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Rutafichero in the schema.
        /// </summary>
        public virtual string Rutafichero
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Version in the schema.
        /// </summary>
        public virtual int Version
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpeticionario in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idpeticionario
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fecha in the schema.
        /// </summary>
        public virtual System.DateTime Fecha
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Metadata in the schema.
        /// </summary>
        public virtual string Metadata
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Documentonovalido in the schema.
        /// </summary>
        public virtual bool Documentonovalido
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechamodificacion in the schema.
        /// </summary>
        public virtual System.DateTime Fechamodificacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Peticionarios in the schema.
        /// </summary>
        public virtual Peticionarios Peticionarios
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for GestordocumentalDocumento in the schema.
        /// </summary>
        public virtual GestordocumentalDocumento GestordocumentalDocumento
        {
            get;
            set;
        }
    }

}
