//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Gestorinvitados, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Gestorinvitados {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Gestorinvitados constructor in the schema.
        /// </summary>
        public Gestorinvitados()
        {
            this.Descripciongestor = @"N'-";
            this.Linkprograma = @"NULL";
            this.Amec = @"NULL";
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idgestorinvitados in the schema.
        /// </summary>
        public virtual long Idgestorinvitados
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Ideventoformulario in the schema.
        /// </summary>
        public virtual long Ideventoformulario
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idcongreso in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idcongreso
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Descripciongestor in the schema.
        /// </summary>
        public virtual string Descripciongestor
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechainicio in the schema.
        /// </summary>
        public virtual System.DateTime Fechainicio
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechafin in the schema.
        /// </summary>
        public virtual System.DateTime Fechafin
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Poblacion in the schema.
        /// </summary>
        public virtual string Poblacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Linkgestorinvitados in the schema.
        /// </summary>
        public virtual string Linkgestorinvitados
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Linkprograma in the schema.
        /// </summary>
        public virtual string Linkprograma
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Amec in the schema.
        /// </summary>
        public virtual string Amec
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tipogestorinvitados in the schema.
        /// </summary>
        public virtual string Tipogestorinvitados
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Inactivo in the schema.
        /// </summary>
        public virtual int Inactivo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idconfempresa in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idconfempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Confempresa in the schema.
        /// </summary>
        public virtual Confempresa Confempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Congresos in the schema.
        /// </summary>
        public virtual Congresos Congresos
        {
            get;
            set;
        }
    }

}
