//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.GestordocumentalTipoSeccion, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class GestordocumentalTipoSeccion {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for GestordocumentalTipoSeccion constructor in the schema.
        /// </summary>
        public GestordocumentalTipoSeccion()
        {
            this.GestordocumentalTipodocs = new HashSet<GestordocumentalTipodoc>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Nombre in the schema.
        /// </summary>
        public virtual string Nombre
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Inactivo in the schema.
        /// </summary>
        public virtual int Inactivo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for GestordocumentalTipodocs in the schema.
        /// </summary>
        public virtual ISet<GestordocumentalTipodoc> GestordocumentalTipodocs
        {
            get;
            set;
        }
    }

}
