//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Iatas, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Iatas {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Iatas constructor in the schema.
        /// </summary>
        public Iatas()
        {
            this.Idiata = @"N";
            this.Idpoblacion = 0;
            this.Iata = @"N";
            this.Locked = 0;
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idiata in the schema.
        /// </summary>
        public virtual string Idiata
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idconfempresa in the schema.
        /// </summary>
        public virtual int Idconfempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpoblacion in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idpoblacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Iata in the schema.
        /// </summary>
        public virtual string Iata
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }
    }

}
