//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.JustificacionesDatosadicionales, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class JustificacionesDatosadicionales {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for JustificacionesDatosadicionales constructor in the schema.
        /// </summary>
        public JustificacionesDatosadicionales()
        {
            this.Inactivo = 0;
            this.DatosadicionalesReservasPassengers = new HashSet<DatosadicionalesReservasPassenger>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idjustificaciones in the schema.
        /// </summary>
        public virtual long Idjustificaciones
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Justificaciones in the schema.
        /// </summary>
        public virtual string Justificaciones
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Inactivo in the schema.
        /// </summary>
        public virtual short Inactivo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for DatosadicionalesReservasPassengers in the schema.
        /// </summary>
        public virtual ISet<DatosadicionalesReservasPassenger> DatosadicionalesReservasPassengers
        {
            get;
            set;
        }
    }

}
