//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.MensajeReservasPassengerDatosadicionales, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class MensajeReservasPassengerDatosadicionales {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for MensajeReservasPassengerDatosadicionales constructor in the schema.
        /// </summary>
        public MensajeReservasPassengerDatosadicionales()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idmensaje in the schema.
        /// </summary>
        public virtual long Idmensaje
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipoactividadpax in the schema.
        /// </summary>
        public virtual long Idtipoactividadpax
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipoasistente in the schema.
        /// </summary>
        public virtual long Idtipoasistente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idnivelriesgo in the schema.
        /// </summary>
        public virtual long Idnivelriesgo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Mensaje in the schema.
        /// </summary>
        public virtual string Mensaje
        {
            get;
            set;
        }
    }

}
