//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.NivelRiesgoHcpDatosadicionales, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class NivelRiesgoHcpDatosadicionales {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for NivelRiesgoHcpDatosadicionales constructor in the schema.
        /// </summary>
        public NivelRiesgoHcpDatosadicionales()
        {
            this.DatosadicionalesReservasPassengers = new HashSet<DatosadicionalesReservasPassenger>();
            this.PeticionGrupos = new HashSet<PeticionGrupos>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idnivelriesgo in the schema.
        /// </summary>
        public virtual long Idnivelriesgo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Nivelriesgo in the schema.
        /// </summary>
        public virtual string Nivelriesgo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for DatosadicionalesReservasPassengers in the schema.
        /// </summary>
        public virtual ISet<DatosadicionalesReservasPassenger> DatosadicionalesReservasPassengers
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PeticionGrupos in the schema.
        /// </summary>
        public virtual ISet<PeticionGrupos> PeticionGrupos
        {
            get;
            set;
        }
    }

}
