//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Nivelesaprobacion, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Nivelesaprobacion {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Nivelesaprobacion constructor in the schema.
        /// </summary>
        public Nivelesaprobacion()
        {
            this.Amecs = new HashSet<Amecs>();
            this.Peticionarios = new HashSet<Peticionarios>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idnivelaprobacion in the schema.
        /// </summary>
        public virtual long Idnivelaprobacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Nivelaprobacion in the schema.
        /// </summary>
        public virtual string Nivelaprobacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idcargo in the schema.
        /// </summary>
        public virtual long Idcargo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Amecs in the schema.
        /// </summary>
        public virtual ISet<Amecs> Amecs
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Peticionarios in the schema.
        /// </summary>
        public virtual ISet<Peticionarios> Peticionarios
        {
            get;
            set;
        }
    }

}
