//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.PassengersList, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class PassengersList {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for PassengersList constructor in the schema.
        /// </summary>
        public PassengersList()
        {
            this.Idpassengerlist = 0;
            this.Nombre = @"N";
            this.Apel1 = @"N";
            this.Apel2 = @"N";
            this.Nif = @"N";
            this.Direccionemail = @"N";
            this.Telefonocontacto = @"N";
            this.Pasaporte = @"N";
            this.Nombrecentrotrabajo = @"N";
            this.Localidadcentrotrabajo = @"N";
            this.Direccioncentrotrabajo = @"N";
            this.Lugaremisionpasaporte = @"N";
            this.Nacionalidadpasaporte = @"N";
            this.Organizacionvisitaprofesional = @"N";
            this.Direccionprofesionalorganizacion = @"N";
            this.Codigopostal = @"N";
            this.Localidad = @"NULL";
            this.Provincia = @"NULL";
            this.Pais = @"N";
            this.Msdid = @"N";
            this.Descuentoresidente = @"N";
            this.Idnivelriesgo = 6;
            this.Inactivo = 0;
            this.Genesyscode = @"NULL";
            this.Goldenid = @"NULL";
            this.Provincecenter = @"NULL";
            this.Postalcodecenter = @"NULL";
            this.Centercode = @"NULL";
            this.ActividadesPassengersLists = new HashSet<ActividadesPassengersList>();
            this.HotelPassengersLists = new HashSet<HotelPassengersList>();
            this.InsPassengersLists = new HashSet<InsPassengersList>();
            this.ReservasPassengersLists = new HashSet<ReservasPassengersList>();
            this.Transportepassengerslists = new HashSet<Transportepassengerslist>();
            this.PeticionGrupos = new HashSet<PeticionGrupos>();
            this.GestordocumentalDocumentos = new HashSet<GestordocumentalDocumento>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idpassengerlist in the schema.
        /// </summary>
        public virtual int Idpassengerlist
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Nombre in the schema.
        /// </summary>
        public virtual string Nombre
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Apel1 in the schema.
        /// </summary>
        public virtual string Apel1
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Apel2 in the schema.
        /// </summary>
        public virtual string Apel2
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Nif in the schema.
        /// </summary>
        public virtual string Nif
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Direccionemail in the schema.
        /// </summary>
        public virtual string Direccionemail
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Telefonocontacto in the schema.
        /// </summary>
        public virtual string Telefonocontacto
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechanacimiento in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Fechanacimiento
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Pasaporte in the schema.
        /// </summary>
        public virtual string Pasaporte
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechacaducidadpasaporte in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Fechacaducidadpasaporte
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Nombrecentrotrabajo in the schema.
        /// </summary>
        public virtual string Nombrecentrotrabajo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Localidadcentrotrabajo in the schema.
        /// </summary>
        public virtual string Localidadcentrotrabajo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Direccioncentrotrabajo in the schema.
        /// </summary>
        public virtual string Direccioncentrotrabajo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Lugaremisionpasaporte in the schema.
        /// </summary>
        public virtual string Lugaremisionpasaporte
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Nacionalidadpasaporte in the schema.
        /// </summary>
        public virtual string Nacionalidadpasaporte
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Organizacionvisitaprofesional in the schema.
        /// </summary>
        public virtual string Organizacionvisitaprofesional
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Direccionprofesionalorganizacion in the schema.
        /// </summary>
        public virtual string Direccionprofesionalorganizacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Codigopostal in the schema.
        /// </summary>
        public virtual string Codigopostal
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Localidad in the schema.
        /// </summary>
        public virtual string Localidad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Provincia in the schema.
        /// </summary>
        public virtual string Provincia
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Pais in the schema.
        /// </summary>
        public virtual string Pais
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Msdid in the schema.
        /// </summary>
        public virtual string Msdid
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtratamiento in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idtratamiento
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Iddistrito in the schema.
        /// </summary>
        public virtual System.Nullable<int> Iddistrito
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idespecialidad in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idespecialidad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Descuentoresidente in the schema.
        /// </summary>
        public virtual string Descuentoresidente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idnivelriesgo in the schema.
        /// </summary>
        public virtual long Idnivelriesgo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Inactivo in the schema.
        /// </summary>
        public virtual System.Nullable<int> Inactivo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Genesyscode in the schema.
        /// </summary>
        public virtual string Genesyscode
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Goldenid in the schema.
        /// </summary>
        public virtual string Goldenid
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Provincecenter in the schema.
        /// </summary>
        public virtual string Provincecenter
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Postalcodecenter in the schema.
        /// </summary>
        public virtual string Postalcodecenter
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Updatedate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Updatedate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Centercode in the schema.
        /// </summary>
        public virtual string Centercode
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Internacional in the schema.
        /// </summary>
        public virtual System.Nullable<int> Internacional
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Peticionario in the schema.
        /// </summary>
        public virtual System.Nullable<int> Peticionario
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdpassengerlistoriginGp in the schema.
        /// </summary>
        public virtual System.Nullable<int> IdpassengerlistoriginGp
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdpassengerlistoriginMt in the schema.
        /// </summary>
        public virtual System.Nullable<int> IdpassengerlistoriginMt
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdpassengerlistoriginAmex in the schema.
        /// </summary>
        public virtual System.Nullable<int> IdpassengerlistoriginAmex
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ActividadesPassengersLists in the schema.
        /// </summary>
        public virtual ISet<ActividadesPassengersList> ActividadesPassengersLists
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for HotelPassengersLists in the schema.
        /// </summary>
        public virtual ISet<HotelPassengersList> HotelPassengersLists
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for InsPassengersLists in the schema.
        /// </summary>
        public virtual ISet<InsPassengersList> InsPassengersLists
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Especialidades in the schema.
        /// </summary>
        public virtual Especialidades Especialidades
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tratamientos in the schema.
        /// </summary>
        public virtual Tratamientos Tratamientos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for NivelRiesgoHcp in the schema.
        /// </summary>
        public virtual NivelRiesgoHcp NivelRiesgoHcp
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ReservasPassengersLists in the schema.
        /// </summary>
        public virtual ISet<ReservasPassengersList> ReservasPassengersLists
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Transportepassengerslists in the schema.
        /// </summary>
        public virtual ISet<Transportepassengerslist> Transportepassengerslists
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PeticionGrupos in the schema.
        /// </summary>
        public virtual ISet<PeticionGrupos> PeticionGrupos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for GestordocumentalDocumentos in the schema.
        /// </summary>
        public virtual ISet<GestordocumentalDocumento> GestordocumentalDocumentos
        {
            get;
            set;
        }
    }

}
