//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.PeticionGruposAbc, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class PeticionGruposAbc {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for PeticionGruposAbc constructor in the schema.
        /// </summary>
        public PeticionGruposAbc()
        {
            this.Countryems = @"NULL";
            this.Apellidospassenger = @"NULL";
            this.Nombrepassenger = @"NULL";
            this.Msdid = @"NULL";
            this.Nombrecompletopeticionario = @"NULL";
            this.Lugarcongreso = @"NULL";
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idpeticiongrupo in the schema.
        /// </summary>
        public virtual int Idpeticiongrupo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idcongreso in the schema.
        /// </summary>
        public virtual System.Nullable<long> Idcongreso
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idexpediente in the schema.
        /// </summary>
        public virtual System.Nullable<long> Idexpediente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Countryems in the schema.
        /// </summary>
        public virtual string Countryems
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Apellidospassenger in the schema.
        /// </summary>
        public virtual string Apellidospassenger
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Nombrepassenger in the schema.
        /// </summary>
        public virtual string Nombrepassenger
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Msdid in the schema.
        /// </summary>
        public virtual string Msdid
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Nombrecompletopeticionario in the schema.
        /// </summary>
        public virtual string Nombrecompletopeticionario
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Lugarcongreso in the schema.
        /// </summary>
        public virtual string Lugarcongreso
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpaisabc in the schema.
        /// </summary>
        public virtual System.Nullable<long> Idpaisabc
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipoabc in the schema.
        /// </summary>
        public virtual System.Nullable<long> Idtipoabc
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Currency in the schema.
        /// </summary>
        public virtual System.Nullable<long> Currency
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Totalrestauracion in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> Totalrestauracion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Totalinscripciones in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> Totalinscripciones
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Totalalojamiento in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> Totalalojamiento
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Totalotrosgastos in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> Totalotrosgastos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Totaltransporte in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> Totaltransporte
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Totalhonorarios in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> Totalhonorarios
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechapeticion in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Fechapeticion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Lastup in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Lastup
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Ideventosforms in the schema.
        /// </summary>
        public virtual System.Nullable<long> Ideventosforms
        {
            get;
            set;
        }
    }

}
