//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.PeticionesActividad, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class PeticionesActividad {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for PeticionesActividad constructor in the schema.
        /// </summary>
        public PeticionesActividad()
        {
            this.Idpeticionactividad = 0;
            this.Nombre = @"N";
            this.Idpoblacion = 0;
            this.Idespecialidad = 0;
            this.Sede = @"N";
            this.Idtipocongreso = 0;
            this.Locked = 0;
            this.Internacional = 0;
            this.UrlWeb = @"N";
            this.EmailSecretaria = @"N";
            this.Especialidad = @"N";
            this.Idpeticionario = 0;
            this.Comunicar = 0;
            this.ValoracionFarmaindustria = @"N";
            this.Amecs = new HashSet<Amec>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idpeticionactividad in the schema.
        /// </summary>
        public virtual int Idpeticionactividad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Nombre in the schema.
        /// </summary>
        public virtual string Nombre
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Desde in the schema.
        /// </summary>
        public virtual System.DateTime Desde
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Hasta in the schema.
        /// </summary>
        public virtual System.DateTime Hasta
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpoblacion in the schema.
        /// </summary>
        public virtual int Idpoblacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idcongreso in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idcongreso
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idespecialidad in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idespecialidad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Sede in the schema.
        /// </summary>
        public virtual string Sede
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipocongreso in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idtipocongreso
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Internacional in the schema.
        /// </summary>
        public virtual System.Nullable<short> Internacional
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UrlWeb in the schema.
        /// </summary>
        public virtual string UrlWeb
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EmailSecretaria in the schema.
        /// </summary>
        public virtual string EmailSecretaria
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Especialidad in the schema.
        /// </summary>
        public virtual string Especialidad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechacreacion in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Fechacreacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpeticionario in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idpeticionario
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Comunicar in the schema.
        /// </summary>
        public virtual System.Nullable<short> Comunicar
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ValoracionFarmaindustria in the schema.
        /// </summary>
        public virtual string ValoracionFarmaindustria
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idconfempresa in the schema.
        /// </summary>
        public virtual int Idconfempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Amecs in the schema.
        /// </summary>
        public virtual ISet<Amec> Amecs
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Confempresa in the schema.
        /// </summary>
        public virtual Confempresa Confempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Congresos in the schema.
        /// </summary>
        public virtual Congresos Congresos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Peticionarios in the schema.
        /// </summary>
        public virtual Peticionarios Peticionarios
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tiposcongreso in the schema.
        /// </summary>
        public virtual Tiposcongreso Tiposcongreso
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Poblaciones in the schema.
        /// </summary>
        public virtual Poblaciones Poblaciones
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Especialidades in the schema.
        /// </summary>
        public virtual Especialidades Especialidades
        {
            get;
            set;
        }
    }

}
