//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Peticionarios, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Peticionarios {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Peticionarios constructor in the schema.
        /// </summary>
        public Peticionarios()
        {
            this.Idpeticionario = 0;
            this.Fkidempresa = 0;
            this.Login = @"NULL";
            this.Password = @"NULL";
            this.Wein = @"N";
            this.Nombre = @"N";
            this.Apellido1 = @"N";
            this.Apellido2 = @"N";
            this.Direccion = @"N";
            this.Codpostal = @"N";
            this.Telefono = @"N";
            this.Extension = @"N";
            this.Movil = @"N";
            this.Email = @"N";
            this.Inactivo = 0;
            this.Locked = 0;
            this.Atencionprimaria = 0;
            this.Descuentoresidente = @"N";
            this.Administrador = 0;
            this.Amex = @"NULL";
            this.Emailpiloto = @"NULL";
            this.Emailbueno = @"NULL";
            this.Medico = false;
            this.Legal = false;
            this.Executive = false;
            this.Director = false;
            this.Gerente = false;
            this.Assistant = false;
            this.Altocargo = false;
            this.Externaluser = false;
            this.Amecs_idsolicitante = new HashSet<Amecs>();
            this.Amecs_idcreadopor = new HashSet<Amecs>();
            this.Congresos = new HashSet<Congresos>();
            this.Expedientes = new HashSet<Expediente>();
            this.Reservasviajes = new HashSet<Reservasviajes>();
            this.PeticionesActividads = new HashSet<PeticionesActividad>();
            this.PeticionGrupos = new HashSet<PeticionGrupos>();
            this.AgencyUserApprovalStructures_IdPeticionario = new HashSet<AgencyUserApprovalStructure>();
            this.AgencyUserApprovalStructures_IdPeticionarioManager = new HashSet<AgencyUserApprovalStructure>();
            this.Aprobadoramecs_idaprobador = new HashSet<Aprobadoramec>();
            this.Aprobadoramecs_idcreadopor = new HashSet<Aprobadoramec>();
            this.GestordocumentalDocumentos = new HashSet<GestordocumentalDocumento>();
            this.GestordocumentalDocumentoversions = new HashSet<GestordocumentalDocumentoversion>();
            this.PeticionariosEmpleadosgps = new HashSet<PeticionariosEmpleadosgp>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idpeticionario in the schema.
        /// </summary>
        public virtual int Idpeticionario
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fkidempresa in the schema.
        /// </summary>
        public virtual int Fkidempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Login in the schema.
        /// </summary>
        public virtual string Login
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Password in the schema.
        /// </summary>
        public virtual string Password
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Wein in the schema.
        /// </summary>
        public virtual string Wein
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idcargo in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idcargo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtratamiento in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idtratamiento
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Nombre in the schema.
        /// </summary>
        public virtual string Nombre
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Apellido1 in the schema.
        /// </summary>
        public virtual string Apellido1
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Apellido2 in the schema.
        /// </summary>
        public virtual string Apellido2
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Direccion in the schema.
        /// </summary>
        public virtual string Direccion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpoblacion in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idpoblacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Codpostal in the schema.
        /// </summary>
        public virtual string Codpostal
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Telefono in the schema.
        /// </summary>
        public virtual string Telefono
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Extension in the schema.
        /// </summary>
        public virtual string Extension
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Movil in the schema.
        /// </summary>
        public virtual string Movil
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Email in the schema.
        /// </summary>
        public virtual string Email
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Inactivo in the schema.
        /// </summary>
        public virtual short Inactivo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Observaciones in the schema.
        /// </summary>
        public virtual string Observaciones
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechaprimeraccesoportal in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Fechaprimeraccesoportal
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idarea in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idarea
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idregion in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idregion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Iddistrito in the schema.
        /// </summary>
        public virtual System.Nullable<int> Iddistrito
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Atencionprimaria in the schema.
        /// </summary>
        public virtual System.Nullable<short> Atencionprimaria
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Descuentoresidente in the schema.
        /// </summary>
        public virtual string Descuentoresidente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idunidad in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idunidad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpeticionarioresponsable in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idpeticionarioresponsable
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Administrador in the schema.
        /// </summary>
        public virtual System.Nullable<short> Administrador
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Amex in the schema.
        /// </summary>
        public virtual string Amex
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FechaCaducidad in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> FechaCaducidad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idnivelaprobacion in the schema.
        /// </summary>
        public virtual System.Nullable<long> Idnivelaprobacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Emailpiloto in the schema.
        /// </summary>
        public virtual string Emailpiloto
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Emailbueno in the schema.
        /// </summary>
        public virtual string Emailbueno
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Poblacion in the schema.
        /// </summary>
        public virtual string Poblacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idposition in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idposition
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Iddepartament in the schema.
        /// </summary>
        public virtual System.Nullable<int> Iddepartament
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idsaleforce in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idsaleforce
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Iddistrict in the schema.
        /// </summary>
        public virtual System.Nullable<int> Iddistrict
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Weinmanager in the schema.
        /// </summary>
        public virtual string Weinmanager
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Creationdate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Creationdate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Lastupdatedate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Lastupdatedate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Medico in the schema.
        /// </summary>
        public virtual System.Nullable<bool> Medico
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Legal in the schema.
        /// </summary>
        public virtual System.Nullable<bool> Legal
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Executive in the schema.
        /// </summary>
        public virtual System.Nullable<bool> Executive
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Director in the schema.
        /// </summary>
        public virtual System.Nullable<bool> Director
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Gerente in the schema.
        /// </summary>
        public virtual System.Nullable<bool> Gerente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Assistant in the schema.
        /// </summary>
        public virtual System.Nullable<bool> Assistant
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Altocargo in the schema.
        /// </summary>
        public virtual System.Nullable<bool> Altocargo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Levelcode in the schema.
        /// </summary>
        public virtual string Levelcode
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Externaluser in the schema.
        /// </summary>
        public virtual bool Externaluser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idconfempresa in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idconfempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Newco in the schema.
        /// </summary>
        public virtual bool Newco
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Amecs_idsolicitante in the schema.
        /// </summary>
        public virtual ISet<Amecs> Amecs_idsolicitante
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Amecs_idcreadopor in the schema.
        /// </summary>
        public virtual ISet<Amecs> Amecs_idcreadopor
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Congresos in the schema.
        /// </summary>
        public virtual ISet<Congresos> Congresos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Expedientes in the schema.
        /// </summary>
        public virtual ISet<Expediente> Expedientes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Nivelesaprobacion in the schema.
        /// </summary>
        public virtual Nivelesaprobacion Nivelesaprobacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Poblaciones in the schema.
        /// </summary>
        public virtual Poblaciones Poblaciones
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tratamientos in the schema.
        /// </summary>
        public virtual Tratamientos Tratamientos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Departaments in the schema.
        /// </summary>
        public virtual Departaments Departaments
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Salesforce in the schema.
        /// </summary>
        public virtual Salesforce Salesforce
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Districts in the schema.
        /// </summary>
        public virtual Districts Districts
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Reservasviajes in the schema.
        /// </summary>
        public virtual ISet<Reservasviajes> Reservasviajes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PeticionesActividads in the schema.
        /// </summary>
        public virtual ISet<PeticionesActividad> PeticionesActividads
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PeticionGrupos in the schema.
        /// </summary>
        public virtual ISet<PeticionGrupos> PeticionGrupos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AgencyUserApprovalStructures_IdPeticionario in the schema.
        /// </summary>
        public virtual ISet<AgencyUserApprovalStructure> AgencyUserApprovalStructures_IdPeticionario
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AgencyUserApprovalStructures_IdPeticionarioManager in the schema.
        /// </summary>
        public virtual ISet<AgencyUserApprovalStructure> AgencyUserApprovalStructures_IdPeticionarioManager
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Aprobadoramecs_idaprobador in the schema.
        /// </summary>
        public virtual ISet<Aprobadoramec> Aprobadoramecs_idaprobador
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Aprobadoramecs_idcreadopor in the schema.
        /// </summary>
        public virtual ISet<Aprobadoramec> Aprobadoramecs_idcreadopor
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for GestordocumentalDocumentos in the schema.
        /// </summary>
        public virtual ISet<GestordocumentalDocumento> GestordocumentalDocumentos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for GestordocumentalDocumentoversions in the schema.
        /// </summary>
        public virtual ISet<GestordocumentalDocumentoversion> GestordocumentalDocumentoversions
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PeticionariosEmpleadosgps in the schema.
        /// </summary>
        public virtual ISet<PeticionariosEmpleadosgp> PeticionariosEmpleadosgps
        {
            get;
            set;
        }
    }

}
