//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.PeticionGrupos, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class PeticionGrupos {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for PeticionGrupos constructor in the schema.
        /// </summary>
        public PeticionGrupos()
        {
            this.Unidad = @"NULL";
            this.Region = @"NULL";
            this.Area = @"NULL";
            this.NombrePeticionario = @"NULL";
            this.ApellidoPeticionario = @"NULL";
            this.Idamec = @"NULL";
            this.Evento = @"NULL";
            this.Apellido1 = @"NULL";
            this.Nombre = @"NULL";
            this.Msdid = @"NULL";
            this.TipoGasto = @"NULL";
            this.EstadoPeticion = @"NULL";
            this.CargoPeticionario = @"NULL";
            this.Numpedido = @"NULL";
            this.Codespecialidad = @"NULL";
            this.EstadoExpediente = @"NULL";
            this.Producto = @"NULL";
            this.PorcentajeProdcuto = @"NULL";
            this.Idestadoreserva = @"NULL";
            this.Distrito = @"NULL";
            this.Apellido2 = @"NULL";
            this.TipoactividadDatosadicionales = @"NULL";
            this.TipoasistenteDatosadicionales = @"NULL";
            this.NivelriesgoDatosadicionales = @"NULL";
            this.JustificacionesDatosadicionales = @"NULL";
            this.FicherogenesisDatosadicionales = @"NULL";
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idpeticiongrupo in the schema.
        /// </summary>
        public virtual long Idpeticiongrupo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idevento in the schema.
        /// </summary>
        public virtual System.Nullable<long> Idevento
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idasistente in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idasistente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idexpediente in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idexpediente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Unidad in the schema.
        /// </summary>
        public virtual string Unidad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Region in the schema.
        /// </summary>
        public virtual string Region
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Area in the schema.
        /// </summary>
        public virtual string Area
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for NombrePeticionario in the schema.
        /// </summary>
        public virtual string NombrePeticionario
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ApellidoPeticionario in the schema.
        /// </summary>
        public virtual string ApellidoPeticionario
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idamec in the schema.
        /// </summary>
        public virtual string Idamec
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Evento in the schema.
        /// </summary>
        public virtual string Evento
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FechaInicioEvento in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> FechaInicioEvento
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Apellido1 in the schema.
        /// </summary>
        public virtual string Apellido1
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Nombre in the schema.
        /// </summary>
        public virtual string Nombre
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Msdid in the schema.
        /// </summary>
        public virtual string Msdid
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for TipoGasto in the schema.
        /// </summary>
        public virtual string TipoGasto
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ImportePeticion in the schema.
        /// </summary>
        public virtual System.Nullable<float> ImportePeticion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FechaPeticion in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> FechaPeticion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EstadoPeticion in the schema.
        /// </summary>
        public virtual string EstadoPeticion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpeticionario in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idpeticionario
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idunidad in the schema.
        /// </summary>
        public virtual System.Nullable<long> Idunidad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idarea in the schema.
        /// </summary>
        public virtual System.Nullable<long> Idarea
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idregion in the schema.
        /// </summary>
        public virtual System.Nullable<long> Idregion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Iddistrito in the schema.
        /// </summary>
        public virtual System.Nullable<long> Iddistrito
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fkidcongreso in the schema.
        /// </summary>
        public virtual System.Nullable<long> Fkidcongreso
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CargoPeticionario in the schema.
        /// </summary>
        public virtual string CargoPeticionario
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Numpedido in the schema.
        /// </summary>
        public virtual string Numpedido
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UltimaActualizacion in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> UltimaActualizacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Codespecialidad in the schema.
        /// </summary>
        public virtual string Codespecialidad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EstadoExpediente in the schema.
        /// </summary>
        public virtual string EstadoExpediente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FechaExpediente in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> FechaExpediente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Producto in the schema.
        /// </summary>
        public virtual string Producto
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PorcentajeProdcuto in the schema.
        /// </summary>
        public virtual string PorcentajeProdcuto
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idcargo in the schema.
        /// </summary>
        public virtual System.Nullable<long> Idcargo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idvalfi in the schema.
        /// </summary>
        public virtual System.Nullable<long> Idvalfi
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FechaFinEvento in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> FechaFinEvento
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipoactividadcongreso in the schema.
        /// </summary>
        public virtual System.Nullable<long> Idtipoactividadcongreso
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idestadoreserva in the schema.
        /// </summary>
        public virtual string Idestadoreserva
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Distrito in the schema.
        /// </summary>
        public virtual string Distrito
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Apellido2 in the schema.
        /// </summary>
        public virtual string Apellido2
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for TipoactividadDatosadicionales in the schema.
        /// </summary>
        public virtual string TipoactividadDatosadicionales
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for TipoasistenteDatosadicionales in the schema.
        /// </summary>
        public virtual string TipoasistenteDatosadicionales
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for NivelriesgoDatosadicionales in the schema.
        /// </summary>
        public virtual string NivelriesgoDatosadicionales
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for JustificacionesDatosadicionales in the schema.
        /// </summary>
        public virtual string JustificacionesDatosadicionales
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FicherogenesisDatosadicionales in the schema.
        /// </summary>
        public virtual string FicherogenesisDatosadicionales
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Iddepartament in the schema.
        /// </summary>
        public virtual System.Nullable<int> Iddepartament
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idsaleforce in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idsaleforce
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Iddistrict in the schema.
        /// </summary>
        public virtual System.Nullable<int> Iddistrict
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idposition in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idposition
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdtipoactividadDatosadicionales in the schema.
        /// </summary>
        public virtual System.Nullable<long> IdtipoactividadDatosadicionales
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdtipoasistenteDatosadicionales in the schema.
        /// </summary>
        public virtual System.Nullable<long> IdtipoasistenteDatosadicionales
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdnivelriesgoDatosadicionales in the schema.
        /// </summary>
        public virtual System.Nullable<long> IdnivelriesgoDatosadicionales
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Expediente in the schema.
        /// </summary>
        public virtual Expediente Expediente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PassengersList in the schema.
        /// </summary>
        public virtual PassengersList PassengersList
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Peticionarios in the schema.
        /// </summary>
        public virtual Peticionarios Peticionarios
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for NivelRiesgoHcpDatosadicionales in the schema.
        /// </summary>
        public virtual NivelRiesgoHcpDatosadicionales NivelRiesgoHcpDatosadicionales
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for TipoActividadPaxDatosadicionales in the schema.
        /// </summary>
        public virtual TipoActividadPaxDatosadicionales TipoActividadPaxDatosadicionales
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for TipoAsistenteDatosadicionales in the schema.
        /// </summary>
        public virtual TipoAsistenteDatosadicionales TipoAsistenteDatosadicionales
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Departaments in the schema.
        /// </summary>
        public virtual Departaments Departaments
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Salesforce in the schema.
        /// </summary>
        public virtual Salesforce Salesforce
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Districts in the schema.
        /// </summary>
        public virtual Districts Districts
        {
            get;
            set;
        }
    }

}
