//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Poblaciones, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Poblaciones {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Poblaciones constructor in the schema.
        /// </summary>
        public Poblaciones()
        {
            this.Idpoblacion = 0;
            this.Poblacion = @"N";
            this.Idprovincia = @"NULL";
            this.Idpais = @"N";
            this.Codpostal = @"N";
            this.Locked = 0;
            this.Idpaisabc = 407;
            this.Inactivo = 0;
            this.Congresos = new HashSet<Congresos>();
            this.Peticionarios = new HashSet<Peticionarios>();
            this.Serviciosreservashotels = new HashSet<Serviciosreservashotel>();
            this.PeticionesActividads = new HashSet<PeticionesActividad>();
            this.Proveedores = new HashSet<Proveedores>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idpoblacion in the schema.
        /// </summary>
        public virtual int Idpoblacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Poblacion in the schema.
        /// </summary>
        public virtual string Poblacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idprovincia in the schema.
        /// </summary>
        public virtual string Idprovincia
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpais in the schema.
        /// </summary>
        public virtual string Idpais
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Codpostal in the schema.
        /// </summary>
        public virtual string Codpostal
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpaisabc in the schema.
        /// </summary>
        public virtual System.Nullable<long> Idpaisabc
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Inactivo in the schema.
        /// </summary>
        public virtual System.Nullable<byte> Inactivo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idconfempresa in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idconfempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Congresos in the schema.
        /// </summary>
        public virtual ISet<Congresos> Congresos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Peticionarios in the schema.
        /// </summary>
        public virtual ISet<Peticionarios> Peticionarios
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Serviciosreservashotels in the schema.
        /// </summary>
        public virtual ISet<Serviciosreservashotel> Serviciosreservashotels
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PeticionesActividads in the schema.
        /// </summary>
        public virtual ISet<PeticionesActividad> PeticionesActividads
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Proveedores in the schema.
        /// </summary>
        public virtual ISet<Proveedores> Proveedores
        {
            get;
            set;
        }
    }

}
