//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Positions, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Positions {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Positions constructor in the schema.
        /// </summary>
        public Positions()
        {
            this.Position = @"N";
            this.Inactivo = 0;
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idposition in the schema.
        /// </summary>
        public virtual int Idposition
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Position in the schema.
        /// </summary>
        public virtual string Position
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Inactivo in the schema.
        /// </summary>
        public virtual System.Nullable<int> Inactivo
        {
            get;
            set;
        }
    }

}
