//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Productos, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Productos {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Productos constructor in the schema.
        /// </summary>
        public Productos()
        {
            this.Idproducto = @"N";
            this.Producto = @"N";
            this.Inactivo = 0;
            this.Locked = 0;
            this.Tarifasactividads = new HashSet<Tarifasactividad>();
            this.Tarifasalojs = new HashSet<Tarifasaloj>();
            this.Tarifasinscripcions = new HashSet<Tarifasinscripcion>();
            this.ProductosPrvs = new HashSet<ProductosPrv>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idproducto in the schema.
        /// </summary>
        public virtual string Idproducto
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Producto in the schema.
        /// </summary>
        public virtual string Producto
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Inactivo in the schema.
        /// </summary>
        public virtual System.Nullable<short> Inactivo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tarifasactividads in the schema.
        /// </summary>
        public virtual ISet<Tarifasactividad> Tarifasactividads
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tarifasalojs in the schema.
        /// </summary>
        public virtual ISet<Tarifasaloj> Tarifasalojs
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tarifasinscripcions in the schema.
        /// </summary>
        public virtual ISet<Tarifasinscripcion> Tarifasinscripcions
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ProductosPrvs in the schema.
        /// </summary>
        public virtual ISet<ProductosPrv> ProductosPrvs
        {
            get;
            set;
        }
    }

}
