//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.ProductosPrv, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class ProductosPrv {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for ProductosPrv constructor in the schema.
        /// </summary>
        public ProductosPrv()
        {
            this.Idproductoprv = 0;
            this.Fkidproveedor = 0;
            this.Desproducto = @"N";
            this.Inactivo = 0;
            this.Idproducto = @"N";
            this.Locked = 0;
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idproductoprv in the schema.
        /// </summary>
        public virtual int Idproductoprv
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fkidproveedor in the schema.
        /// </summary>
        public virtual int Fkidproveedor
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Desproducto in the schema.
        /// </summary>
        public virtual string Desproducto
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Inactivo in the schema.
        /// </summary>
        public virtual short Inactivo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idproducto in the schema.
        /// </summary>
        public virtual string Idproducto
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Productos in the schema.
        /// </summary>
        public virtual Productos Productos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Proveedores in the schema.
        /// </summary>
        public virtual Proveedores Proveedores
        {
            get;
            set;
        }
    }

}
