//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Provincias, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Provincias {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Provincias constructor in the schema.
        /// </summary>
        public Provincias()
        {
            this.Idprovincia = @"N";
            this.Provincia = @"N";
            this.Idpais = @"N";
            this.Idcomunidad = 0;
            this.Locked = 0;
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idprovincia in the schema.
        /// </summary>
        public virtual string Idprovincia
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Provincia in the schema.
        /// </summary>
        public virtual string Provincia
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpais in the schema.
        /// </summary>
        public virtual string Idpais
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idcomunidad in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idcomunidad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Comunidad in the schema.
        /// </summary>
        public virtual Comunidad Comunidad
        {
            get;
            set;
        }
    }

}
