//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Proveedores, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Proveedores {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Proveedores constructor in the schema.
        /// </summary>
        public Proveedores()
        {
            this.Idproveedor = 0;
            this.Idtipoprv = @"N";
            this.Codcia = @"N";
            this.Codamadeus = @"N";
            this.Enlace = @"N";
            this.Proveedor = @"N'--";
            this.Direccion = @"N'--";
            this.Nro = @"N";
            this.Piso = @"N";
            this.Codpostal = @"N";
            this.Telefono = @"N'-";
            this.Fax = @"N";
            this.Email = @"N";
            this.Http = @"N";
            this.Locked = 0;
            this.Congresos = new HashSet<Congresos>();
            this.Serviciosreservashotels = new HashSet<Serviciosreservashotel>();
            this.Tarifasalojs = new HashSet<Tarifasaloj>();
            this.Tarifasinscripcions = new HashSet<Tarifasinscripcion>();
            this.Tramitacionesserviciosreservas_IdProveedor1 = new HashSet<Tramitacionesserviciosreservas>();
            this.Tramitacionesserviciosreservas_IdProveedor2 = new HashSet<Tramitacionesserviciosreservas>();
            this.Tramitacionesserviciosreservas_IdProveedor3 = new HashSet<Tramitacionesserviciosreservas>();
            this.Tramitacionesserviciosreservas_IdProveedor4 = new HashSet<Tramitacionesserviciosreservas>();
            this.Tramitacionesserviciosreservas_IdProveedor5 = new HashSet<Tramitacionesserviciosreservas>();
            this.Tramitacionesserviciosreservas_IdProveedor6 = new HashSet<Tramitacionesserviciosreservas>();
            this.ProductosPrvs = new HashSet<ProductosPrv>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idproveedor in the schema.
        /// </summary>
        public virtual int Idproveedor
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipoprv in the schema.
        /// </summary>
        public virtual string Idtipoprv
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Codcia in the schema.
        /// </summary>
        public virtual string Codcia
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Codamadeus in the schema.
        /// </summary>
        public virtual string Codamadeus
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Enlace in the schema.
        /// </summary>
        public virtual string Enlace
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Proveedor in the schema.
        /// </summary>
        public virtual string Proveedor
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Direccion in the schema.
        /// </summary>
        public virtual string Direccion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Nro in the schema.
        /// </summary>
        public virtual string Nro
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Piso in the schema.
        /// </summary>
        public virtual string Piso
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpoblacion in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idpoblacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Codpostal in the schema.
        /// </summary>
        public virtual string Codpostal
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Telefono in the schema.
        /// </summary>
        public virtual string Telefono
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fax in the schema.
        /// </summary>
        public virtual string Fax
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Email in the schema.
        /// </summary>
        public virtual string Email
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Http in the schema.
        /// </summary>
        public virtual string Http
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idconfempresa in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idconfempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Congresos in the schema.
        /// </summary>
        public virtual ISet<Congresos> Congresos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Serviciosreservashotels in the schema.
        /// </summary>
        public virtual ISet<Serviciosreservashotel> Serviciosreservashotels
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tarifasalojs in the schema.
        /// </summary>
        public virtual ISet<Tarifasaloj> Tarifasalojs
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tarifasinscripcions in the schema.
        /// </summary>
        public virtual ISet<Tarifasinscripcion> Tarifasinscripcions
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tramitacionesserviciosreservas_IdProveedor1 in the schema.
        /// </summary>
        public virtual ISet<Tramitacionesserviciosreservas> Tramitacionesserviciosreservas_IdProveedor1
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tramitacionesserviciosreservas_IdProveedor2 in the schema.
        /// </summary>
        public virtual ISet<Tramitacionesserviciosreservas> Tramitacionesserviciosreservas_IdProveedor2
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tramitacionesserviciosreservas_IdProveedor3 in the schema.
        /// </summary>
        public virtual ISet<Tramitacionesserviciosreservas> Tramitacionesserviciosreservas_IdProveedor3
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tramitacionesserviciosreservas_IdProveedor4 in the schema.
        /// </summary>
        public virtual ISet<Tramitacionesserviciosreservas> Tramitacionesserviciosreservas_IdProveedor4
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tramitacionesserviciosreservas_IdProveedor5 in the schema.
        /// </summary>
        public virtual ISet<Tramitacionesserviciosreservas> Tramitacionesserviciosreservas_IdProveedor5
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tramitacionesserviciosreservas_IdProveedor6 in the schema.
        /// </summary>
        public virtual ISet<Tramitacionesserviciosreservas> Tramitacionesserviciosreservas_IdProveedor6
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Poblaciones in the schema.
        /// </summary>
        public virtual Poblaciones Poblaciones
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for TiposPrv in the schema.
        /// </summary>
        public virtual TiposPrv TiposPrv
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ProductosPrvs in the schema.
        /// </summary>
        public virtual ISet<ProductosPrv> ProductosPrvs
        {
            get;
            set;
        }
    }

}
