//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.QServiceQuery, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class QServiceQuery {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for QServiceQuery constructor in the schema.
        /// </summary>
        public QServiceQuery()
        {
            this.Hashedkey = @"NULL";
            this.Randonguid = @"NULL";
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idservicequery in the schema.
        /// </summary>
        public virtual int Idservicequery
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idservicesuscriptor in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idservicesuscriptor
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Hashedkey in the schema.
        /// </summary>
        public virtual string Hashedkey
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Createdate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Createdate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Updatedate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Updatedate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Randonguid in the schema.
        /// </summary>
        public virtual string Randonguid
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for QServiceSuscriptor in the schema.
        /// </summary>
        public virtual QServiceSuscriptor QServiceSuscriptor
        {
            get;
            set;
        }
    }

}
