//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.QServiceSuscriptor, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class QServiceSuscriptor {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for QServiceSuscriptor constructor in the schema.
        /// </summary>
        public QServiceSuscriptor()
        {
            this.QServiceQueries = new HashSet<QServiceQuery>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idservicesuscriptor in the schema.
        /// </summary>
        public virtual int Idservicesuscriptor
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idservice in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idservice
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idsuscriptor in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idsuscriptor
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for QService in the schema.
        /// </summary>
        public virtual QService QService
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for QServiceQueries in the schema.
        /// </summary>
        public virtual ISet<QServiceQuery> QServiceQueries
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for QSuscriptor in the schema.
        /// </summary>
        public virtual QSuscriptor QSuscriptor
        {
            get;
            set;
        }
    }

}
