//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.QSuscriptor, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class QSuscriptor {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for QSuscriptor constructor in the schema.
        /// </summary>
        public QSuscriptor()
        {
            this.Publickey = @"NULL";
            this.Privatekey = @"NULL";
            this.Title = @"NULL";
            this.QServiceStatistics = new HashSet<QServiceStatistics>();
            this.QServiceSuscriptors = new HashSet<QServiceSuscriptor>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idsuscriptor in the schema.
        /// </summary>
        public virtual int Idsuscriptor
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Publickey in the schema.
        /// </summary>
        public virtual string Publickey
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Privatekey in the schema.
        /// </summary>
        public virtual string Privatekey
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Title in the schema.
        /// </summary>
        public virtual string Title
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Status in the schema.
        /// </summary>
        public virtual System.Nullable<int> Status
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Creationdate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Creationdate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for QServiceStatistics in the schema.
        /// </summary>
        public virtual ISet<QServiceStatistics> QServiceStatistics
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for QServiceSuscriptors in the schema.
        /// </summary>
        public virtual ISet<QServiceSuscriptor> QServiceSuscriptors
        {
            get;
            set;
        }
    }

}
