//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.ReservasPassengersList, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class ReservasPassengersList {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for ReservasPassengersList constructor in the schema.
        /// </summary>
        public ReservasPassengersList()
        {
            this.Idreservapassengerlist = 0;
            this.Idpassengerlist = 0;
            this.Locked = 0;
            this.Idxpediente = 0;
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idreservapassengerlist in the schema.
        /// </summary>
        public virtual int Idreservapassengerlist
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpassengerlist in the schema.
        /// </summary>
        public virtual int Idpassengerlist
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idxpediente in the schema.
        /// </summary>
        public virtual int Idxpediente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Expediente in the schema.
        /// </summary>
        public virtual Expediente Expediente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PassengersList in the schema.
        /// </summary>
        public virtual PassengersList PassengersList
        {
            get;
            set;
        }
    }

}
