//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Reservasviajes, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Reservasviajes {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Reservasviajes constructor in the schema.
        /// </summary>
        public Reservasviajes()
        {
            this.Idreserva = 0;
            this.Idestado = @"N";
            this.Lastlog = @"N";
            this.Idpeticionario = 0;
            this.Mainreserva = @"N";
            this.Fkidexpediente = 0;
            this.Locked = 0;
            this.Serviciosreservasviajes = new HashSet<Serviciosreservasviajes>();
            this.EstadosReservas = new HashSet<EstadosReservas>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idreserva in the schema.
        /// </summary>
        public virtual int Idreserva
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Reserva in the schema.
        /// </summary>
        public virtual string Reserva
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechapeticion in the schema.
        /// </summary>
        public virtual System.DateTime Fechapeticion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idestado in the schema.
        /// </summary>
        public virtual string Idestado
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Lastupd in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Lastupd
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Lastlog in the schema.
        /// </summary>
        public virtual string Lastlog
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpeticionario in the schema.
        /// </summary>
        public virtual int Idpeticionario
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Observaciones in the schema.
        /// </summary>
        public virtual string Observaciones
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ObservAgencia in the schema.
        /// </summary>
        public virtual string ObservAgencia
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Mainreserva in the schema.
        /// </summary>
        public virtual string Mainreserva
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fkidexpediente in the schema.
        /// </summary>
        public virtual int Fkidexpediente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Expediente in the schema.
        /// </summary>
        public virtual Expediente Expediente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Peticionarios in the schema.
        /// </summary>
        public virtual Peticionarios Peticionarios
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Estadosreservas in the schema.
        /// </summary>
        public virtual Estadosreservas Estadosreservas
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Serviciosreservasviajes in the schema.
        /// </summary>
        public virtual ISet<Serviciosreservasviajes> Serviciosreservasviajes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EstadosReservas in the schema.
        /// </summary>
        public virtual ISet<EstadosReservas> EstadosReservas
        {
            get;
            set;
        }
    }

}
