//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Serviciosreservashotel, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Serviciosreservashotel {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Serviciosreservashotel constructor in the schema.
        /// </summary>
        public Serviciosreservashotel()
        {
            this.Idserviciohotel = 0;
            this.Idpais = @"N";
            this.Pais = @"N";
            this.Idprovincia = @"N";
            this.Provincia = @"N";
            this.Idpoblacion = 0;
            this.Poblacion = @"N";
            this.Idproveedor = 0;
            this.Idtipoaloj = 0;
            this.Categoria = @"N";
            this.Idtipohab = @"N";
            this.NumHabitaciones = 0;
            this.DescTipoalojamiento = @"N";
            this.DescIdtipoHabitacion = @"N";
            this.Idtarifaaloj = 0;
            this.Pvp = 0;
            this.Locked = 0;
            this.HotelPassengersLists = new HashSet<HotelPassengersList>();
            this.Serviciosreservasviajes = new HashSet<Serviciosreservasviajes>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idserviciohotel in the schema.
        /// </summary>
        public virtual int Idserviciohotel
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechahorallegada in the schema.
        /// </summary>
        public virtual System.DateTime Fechahorallegada
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechahorasalida in the schema.
        /// </summary>
        public virtual System.DateTime Fechahorasalida
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpais in the schema.
        /// </summary>
        public virtual string Idpais
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Pais in the schema.
        /// </summary>
        public virtual string Pais
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idprovincia in the schema.
        /// </summary>
        public virtual string Idprovincia
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Provincia in the schema.
        /// </summary>
        public virtual string Provincia
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idpoblacion in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idpoblacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Poblacion in the schema.
        /// </summary>
        public virtual string Poblacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idproveedor in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idproveedor
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Hotel in the schema.
        /// </summary>
        public virtual string Hotel
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipoaloj in the schema.
        /// </summary>
        public virtual int Idtipoaloj
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Categoria in the schema.
        /// </summary>
        public virtual string Categoria
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Observaciones in the schema.
        /// </summary>
        public virtual string Observaciones
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipohab in the schema.
        /// </summary>
        public virtual string Idtipohab
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for NumHabitaciones in the schema.
        /// </summary>
        public virtual System.Nullable<int> NumHabitaciones
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for DescTipoalojamiento in the schema.
        /// </summary>
        public virtual string DescTipoalojamiento
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for DescIdtipoHabitacion in the schema.
        /// </summary>
        public virtual string DescIdtipoHabitacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtarifaaloj in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idtarifaaloj
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Pvp in the schema.
        /// </summary>
        public virtual System.Nullable<double> Pvp
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idconfempresa in the schema.
        /// </summary>
        public virtual int Idconfempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Confempresa in the schema.
        /// </summary>
        public virtual Confempresa Confempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for HotelPassengersLists in the schema.
        /// </summary>
        public virtual ISet<HotelPassengersList> HotelPassengersLists
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tarifasaloj in the schema.
        /// </summary>
        public virtual Tarifasaloj Tarifasaloj
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tiposaloj in the schema.
        /// </summary>
        public virtual Tiposaloj Tiposaloj
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for TiposHab in the schema.
        /// </summary>
        public virtual TiposHab TiposHab
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Poblaciones in the schema.
        /// </summary>
        public virtual Poblaciones Poblaciones
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Proveedores in the schema.
        /// </summary>
        public virtual Proveedores Proveedores
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Serviciosreservasviajes in the schema.
        /// </summary>
        public virtual ISet<Serviciosreservasviajes> Serviciosreservasviajes
        {
            get;
            set;
        }
    }

}
