//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Serviciosreservasviajes, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Serviciosreservasviajes {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Serviciosreservasviajes constructor in the schema.
        /// </summary>
        public Serviciosreservasviajes()
        {
            this.Idservicio = 0;
            this.Idreserva = 0;
            this.Idtipobono = @"N";
            this.Cotizado = 0;
            this.Locked = 0;
            this.Importereserva = 0;
            this.Tramitacionesserviciosreservas = new HashSet<Tramitacionesserviciosreservas>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idservicio in the schema.
        /// </summary>
        public virtual int Idservicio
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idreserva in the schema.
        /// </summary>
        public virtual int Idreserva
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipobono in the schema.
        /// </summary>
        public virtual string Idtipobono
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechapeticion in the schema.
        /// </summary>
        public virtual System.DateTime Fechapeticion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Resumenservicio in the schema.
        /// </summary>
        public virtual string Resumenservicio
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Cotizado in the schema.
        /// </summary>
        public virtual System.Nullable<int> Cotizado
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idservicioinscripcion in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idservicioinscripcion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idserviciohotel in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idserviciohotel
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idservicioactividad in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idservicioactividad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idserviciotransporte in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idserviciotransporte
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdtransporteServicioavion1 in the schema.
        /// </summary>
        public virtual System.Nullable<int> IdtransporteServicioavion1
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdtransporteServiciotren1 in the schema.
        /// </summary>
        public virtual System.Nullable<int> IdtransporteServiciotren1
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdtransporteServiciocar1 in the schema.
        /// </summary>
        public virtual System.Nullable<int> IdtransporteServiciocar1
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Importereserva in the schema.
        /// </summary>
        public virtual System.Nullable<double> Importereserva
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Reservasviajes in the schema.
        /// </summary>
        public virtual Reservasviajes Reservasviajes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Serviciosreservasactividades in the schema.
        /// </summary>
        public virtual Serviciosreservasactividades Serviciosreservasactividades
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Serviciosreservashotel in the schema.
        /// </summary>
        public virtual Serviciosreservashotel Serviciosreservashotel
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Serviciosreservasinscripciones in the schema.
        /// </summary>
        public virtual Serviciosreservasinscripciones Serviciosreservasinscripciones
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Serviciosreservastransporte in the schema.
        /// </summary>
        public virtual Serviciosreservastransporte Serviciosreservastransporte
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tramitacionesserviciosreservas in the schema.
        /// </summary>
        public virtual ISet<Tramitacionesserviciosreservas> Tramitacionesserviciosreservas
        {
            get;
            set;
        }
    }

}
