//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for ServiciosMethodsExecutor in the schema.
    /// </summary>
    public partial class ServiciosMethodsExecutor
    {

        private NHibernate.ISession session;

        /// <summary>
        /// There are no comments for ServiciosMethodsExecutor constructor in the schema.
        /// </summary>
        public ServiciosMethodsExecutor(NHibernate.ISession session)
        {
          this.session = session;
        }

    
        /// <summary>
        /// There are no comments for SpObtenerAmecsPuedoVer in the schema.
        /// </summary>
        public void SpObtenerAmecsPuedoVer(System.Nullable<int> idPeticionario, System.Nullable<int> isCreateMode)
        {

            NHibernate.IQuery query = session.GetNamedQuery(@"SpObtenerAmecsPuedoVer");
            query.SetParameter(@"idPeticionario", idPeticionario);
            query.SetParameter(@"isCreateMode", isCreateMode);
            query.List();
        }

    
        /// <summary>
        /// There are no comments for SpObtenerAmecsPuedoVer in the schema.
        /// </summary>
        public static void SpObtenerAmecsPuedoVer(NHibernate.ISession session, System.Nullable<int> idPeticionario, System.Nullable<int> isCreateMode)
        {

            NHibernate.IQuery query = session.GetNamedQuery(@"SpObtenerAmecsPuedoVer");
            query.SetParameter(@"idPeticionario", idPeticionario);
            query.SetParameter(@"isCreateMode", isCreateMode);
            query.List();
        }

    
        /// <summary>
        /// There are no comments for SpEjecutarsql in the schema.
        /// </summary>
        public void SpEjecutarsql(string sql)
        {

            NHibernate.IQuery query = session.GetNamedQuery(@"SpEjecutarsql");
            query.SetParameter(@"sql", sql);
            query.List();
        }

    
        /// <summary>
        /// There are no comments for SpEjecutarsql in the schema.
        /// </summary>
        public static void SpEjecutarsql(NHibernate.ISession session, string sql)
        {

            NHibernate.IQuery query = session.GetNamedQuery(@"SpEjecutarsql");
            query.SetParameter(@"sql", sql);
            query.List();
        }
    }

}
