//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Serviciosreservasactividades, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Serviciosreservasactividades {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Serviciosreservasactividades constructor in the schema.
        /// </summary>
        public Serviciosreservasactividades()
        {
            this.Idservicioactividad = 0;
            this.Pvp = 0;
            this.Locked = 0;
            this.Sede = @"N";
            this.Descripcion = @"N";
            this.Tipo = @"NULL";
            this.Horainicio = @"NULL";
            this.Minutosinicio = @"N";
            this.Horafin = @"NULL";
            this.Minutosfin = @"N";
            this.Pax = 0;
            this.ActividadesPassengersLists = new HashSet<ActividadesPassengersList>();
            this.Serviciosreservasviajes = new HashSet<Serviciosreservasviajes>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idservicioactividad in the schema.
        /// </summary>
        public virtual int Idservicioactividad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtarifaactividad in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idtarifaactividad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Observaciones in the schema.
        /// </summary>
        public virtual string Observaciones
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Pvp in the schema.
        /// </summary>
        public virtual System.Nullable<double> Pvp
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Sede in the schema.
        /// </summary>
        public virtual string Sede
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Descripcion in the schema.
        /// </summary>
        public virtual string Descripcion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tipo in the schema.
        /// </summary>
        public virtual string Tipo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechainicio in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Fechainicio
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Horainicio in the schema.
        /// </summary>
        public virtual string Horainicio
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Minutosinicio in the schema.
        /// </summary>
        public virtual string Minutosinicio
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechafin in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Fechafin
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Horafin in the schema.
        /// </summary>
        public virtual string Horafin
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Minutosfin in the schema.
        /// </summary>
        public virtual string Minutosfin
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Pax in the schema.
        /// </summary>
        public virtual System.Nullable<int> Pax
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idconfempresa in the schema.
        /// </summary>
        public virtual int Idconfempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ActividadesPassengersLists in the schema.
        /// </summary>
        public virtual ISet<ActividadesPassengersList> ActividadesPassengersLists
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Confempresa in the schema.
        /// </summary>
        public virtual Confempresa Confempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tarifasactividad in the schema.
        /// </summary>
        public virtual Tarifasactividad Tarifasactividad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Serviciosreservasviajes in the schema.
        /// </summary>
        public virtual ISet<Serviciosreservasviajes> Serviciosreservasviajes
        {
            get;
            set;
        }
    }

}
