//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Serviciosreservasinscripciones, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Serviciosreservasinscripciones {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Serviciosreservasinscripciones constructor in the schema.
        /// </summary>
        public Serviciosreservasinscripciones()
        {
            this.Idservicioinscripcion = 0;
            this.Tipoinscripcion = @"NULL";
            this.Pvp = 0;
            this.Locked = 0;
            this.InsPassengersLists = new HashSet<InsPassengersList>();
            this.Serviciosreservasviajes = new HashSet<Serviciosreservasviajes>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idservicioinscripcion in the schema.
        /// </summary>
        public virtual int Idservicioinscripcion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Inscripcion in the schema.
        /// </summary>
        public virtual string Inscripcion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Envioboletin in the schema.
        /// </summary>
        public virtual string Envioboletin
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tipoinscripcion in the schema.
        /// </summary>
        public virtual string Tipoinscripcion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Otros in the schema.
        /// </summary>
        public virtual string Otros
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Observaciones in the schema.
        /// </summary>
        public virtual string Observaciones
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ObservAgencia in the schema.
        /// </summary>
        public virtual string ObservAgencia
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Iddatosentrega in the schema.
        /// </summary>
        public virtual System.Nullable<int> Iddatosentrega
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtarifainscripcion in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idtarifainscripcion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Pvp in the schema.
        /// </summary>
        public virtual System.Nullable<double> Pvp
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idconfempresa in the schema.
        /// </summary>
        public virtual int Idconfempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Confempresa in the schema.
        /// </summary>
        public virtual Confempresa Confempresa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for InsPassengersLists in the schema.
        /// </summary>
        public virtual ISet<InsPassengersList> InsPassengersLists
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tarifasinscripcion in the schema.
        /// </summary>
        public virtual Tarifasinscripcion Tarifasinscripcion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Serviciosreservasviajes in the schema.
        /// </summary>
        public virtual ISet<Serviciosreservasviajes> Serviciosreservasviajes
        {
            get;
            set;
        }
    }

}
