//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Servicios, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Servicios {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Servicios constructor in the schema.
        /// </summary>
        public Servicios()
        {
            this.Idservicio = @"N";
            this.Idnumerico = 0;
            this.Servicio = @"N";
            this.Locked = 0;
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idservicio in the schema.
        /// </summary>
        public virtual string Idservicio
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idnumerico in the schema.
        /// </summary>
        public virtual int Idnumerico
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Servicio in the schema.
        /// </summary>
        public virtual string Servicio
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }
    }

}
