//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Tarifasinscripcion, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Tarifasinscripcion {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Tarifasinscripcion constructor in the schema.
        /// </summary>
        public Tarifasinscripcion()
        {
            this.Idtarifainscripcion = 0;
            this.Fkidcongreso = 0;
            this.Idtipoinscripcion = 0;
            this.Idproveedor = 0;
            this.Pvp = 0;
            this.Notascli = @"N";
            this.Idproducto = @"N";
            this.Descripcion = @"NULL";
            this.Serviciosreservasinscripciones = new HashSet<Serviciosreservasinscripciones>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idtarifainscripcion in the schema.
        /// </summary>
        public virtual int Idtarifainscripcion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fkidcongreso in the schema.
        /// </summary>
        public virtual int Fkidcongreso
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipoinscripcion in the schema.
        /// </summary>
        public virtual int Idtipoinscripcion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idproveedor in the schema.
        /// </summary>
        public virtual int Idproveedor
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Pvp in the schema.
        /// </summary>
        public virtual double Pvp
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Notascli in the schema.
        /// </summary>
        public virtual string Notascli
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idproducto in the schema.
        /// </summary>
        public virtual string Idproducto
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Prepago in the schema.
        /// </summary>
        public virtual System.Nullable<int> Prepago
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Socio in the schema.
        /// </summary>
        public virtual System.Nullable<int> Socio
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Cancelacion in the schema.
        /// </summary>
        public virtual string Cancelacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FechaValidez in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> FechaValidez
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechainicio in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Fechainicio
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechafin in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Fechafin
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Descripcion in the schema.
        /// </summary>
        public virtual string Descripcion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Congresos in the schema.
        /// </summary>
        public virtual Congresos Congresos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Serviciosreservasinscripciones in the schema.
        /// </summary>
        public virtual ISet<Serviciosreservasinscripciones> Serviciosreservasinscripciones
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tiposinscripcion in the schema.
        /// </summary>
        public virtual Tiposinscripcion Tiposinscripcion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Productos in the schema.
        /// </summary>
        public virtual Productos Productos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Proveedores in the schema.
        /// </summary>
        public virtual Proveedores Proveedores
        {
            get;
            set;
        }
    }

}
