//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Tarifasaloj, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Tarifasaloj {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Tarifasaloj constructor in the schema.
        /// </summary>
        public Tarifasaloj()
        {
            this.Idtarifaaloj = 0;
            this.Fkidcongreso = 0;
            this.Idtipoaloj = 0;
            this.Descripcion = @"N";
            this.Idproveedor = 0;
            this.Idproducto = @"N";
            this.Idtipohab = @"N";
            this.Idservicio = @"N";
            this.Precionoche = 0;
            this.Serviciosreservashotels = new HashSet<Serviciosreservashotel>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idtarifaaloj in the schema.
        /// </summary>
        public virtual int Idtarifaaloj
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fkidcongreso in the schema.
        /// </summary>
        public virtual int Fkidcongreso
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipoaloj in the schema.
        /// </summary>
        public virtual int Idtipoaloj
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Descripcion in the schema.
        /// </summary>
        public virtual string Descripcion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idproveedor in the schema.
        /// </summary>
        public virtual int Idproveedor
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idproducto in the schema.
        /// </summary>
        public virtual string Idproducto
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipohab in the schema.
        /// </summary>
        public virtual string Idtipohab
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idservicio in the schema.
        /// </summary>
        public virtual string Idservicio
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Precionoche in the schema.
        /// </summary>
        public virtual double Precionoche
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Prepago in the schema.
        /// </summary>
        public virtual System.Nullable<int> Prepago
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Socio in the schema.
        /// </summary>
        public virtual System.Nullable<int> Socio
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechainicio in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Fechainicio
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fechafin in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Fechafin
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Cancelacion in the schema.
        /// </summary>
        public virtual string Cancelacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Visible in the schema.
        /// </summary>
        public virtual System.Nullable<int> Visible
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Congresos in the schema.
        /// </summary>
        public virtual Congresos Congresos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Serviciosreservashotels in the schema.
        /// </summary>
        public virtual ISet<Serviciosreservashotel> Serviciosreservashotels
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for TiposHab in the schema.
        /// </summary>
        public virtual TiposHab TiposHab
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tiposaloj in the schema.
        /// </summary>
        public virtual Tiposaloj Tiposaloj
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Productos in the schema.
        /// </summary>
        public virtual Productos Productos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Proveedores in the schema.
        /// </summary>
        public virtual Proveedores Proveedores
        {
            get;
            set;
        }
    }

}
