//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.TiposPrv, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class TiposPrv {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for TiposPrv constructor in the schema.
        /// </summary>
        public TiposPrv()
        {
            this.Idtipoprv = @"N";
            this.Tipoproveedor = @"N";
            this.Idtipobono = @"N";
            this.Locked = 0;
            this.Proveedores = new HashSet<Proveedores>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idtipoprv in the schema.
        /// </summary>
        public virtual string Idtipoprv
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tipoproveedor in the schema.
        /// </summary>
        public virtual string Tipoproveedor
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idtipobono in the schema.
        /// </summary>
        public virtual string Idtipobono
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Proveedores in the schema.
        /// </summary>
        public virtual ISet<Proveedores> Proveedores
        {
            get;
            set;
        }
    }

}
