//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.TiposreservasWeb, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class TiposreservasWeb {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for TiposreservasWeb constructor in the schema.
        /// </summary>
        public TiposreservasWeb()
        {
            this.Idtiporeserva = 0;
            this.Descripcion = @"N";
            this.Locked = 0;
            this.Expedientes = new HashSet<Expediente>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idtiporeserva in the schema.
        /// </summary>
        public virtual int Idtiporeserva
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Descripcion in the schema.
        /// </summary>
        public virtual string Descripcion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Expedientes in the schema.
        /// </summary>
        public virtual ISet<Expediente> Expedientes
        {
            get;
            set;
        }
    }

}
