//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.TiposHab, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class TiposHab {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for TiposHab constructor in the schema.
        /// </summary>
        public TiposHab()
        {
            this.Idtipohab = @"N";
            this.Tipohab = @"N";
            this.Serviciosreservashotels = new HashSet<Serviciosreservashotel>();
            this.Tarifasalojs = new HashSet<Tarifasaloj>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idtipohab in the schema.
        /// </summary>
        public virtual string Idtipohab
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tipohab in the schema.
        /// </summary>
        public virtual string Tipohab
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Ocup in the schema.
        /// </summary>
        public virtual System.Nullable<int> Ocup
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Serviciosreservashotels in the schema.
        /// </summary>
        public virtual ISet<Serviciosreservashotel> Serviciosreservashotels
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tarifasalojs in the schema.
        /// </summary>
        public virtual ISet<Tarifasaloj> Tarifasalojs
        {
            get;
            set;
        }
    }

}
