//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Tipoactividad, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Tipoactividad {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Tipoactividad constructor in the schema.
        /// </summary>
        public Tipoactividad()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idtipoactividad in the schema.
        /// </summary>
        public virtual long Idtipoactividad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tipoactividad1 in the schema.
        /// </summary>
        public virtual string Tipoactividad1
        {
            get;
            set;
        }
    }

}
