//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Tiposcongreso, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Tiposcongreso {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Tiposcongreso constructor in the schema.
        /// </summary>
        public Tiposcongreso()
        {
            this.Idtipocongreso = 0;
            this.Tipocongreso = @"N";
            this.Canal = @"N";
            this.CodTipocongreso = @"N'""""";
            this.Congresos = new HashSet<Congresos>();
            this.PeticionesActividads = new HashSet<PeticionesActividad>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idtipocongreso in the schema.
        /// </summary>
        public virtual int Idtipocongreso
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tipocongreso in the schema.
        /// </summary>
        public virtual string Tipocongreso
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Canal in the schema.
        /// </summary>
        public virtual string Canal
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CodTipocongreso in the schema.
        /// </summary>
        public virtual string CodTipocongreso
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for VisibleWeb in the schema.
        /// </summary>
        public virtual System.Nullable<int> VisibleWeb
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Congresos in the schema.
        /// </summary>
        public virtual ISet<Congresos> Congresos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PeticionesActividads in the schema.
        /// </summary>
        public virtual ISet<PeticionesActividad> PeticionesActividads
        {
            get;
            set;
        }
    }

}
