//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Tiposinscripcion, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Tiposinscripcion {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Tiposinscripcion constructor in the schema.
        /// </summary>
        public Tiposinscripcion()
        {
            this.Idtipoinscripcion = 0;
            this.Tipoinscripcion = @"N";
            this.Tarifasinscripcions = new HashSet<Tarifasinscripcion>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idtipoinscripcion in the schema.
        /// </summary>
        public virtual int Idtipoinscripcion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tipoinscripcion in the schema.
        /// </summary>
        public virtual string Tipoinscripcion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tarifasinscripcions in the schema.
        /// </summary>
        public virtual ISet<Tarifasinscripcion> Tarifasinscripcions
        {
            get;
            set;
        }
    }

}
