//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.TiposBonos, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class TiposBonos {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for TiposBonos constructor in the schema.
        /// </summary>
        public TiposBonos()
        {
            this.Idtipobono = @"N";
            this.Tipobono = @"N";
            this.Locked = 0;
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idtipobono in the schema.
        /// </summary>
        public virtual string Idtipobono
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tipobono in the schema.
        /// </summary>
        public virtual string Tipobono
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }
    }

}
