//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.TiposActividadCongreso, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class TiposActividadCongreso {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for TiposActividadCongreso constructor in the schema.
        /// </summary>
        public TiposActividadCongreso()
        {
            this.Idtipoactividadcongreso = 0;
            this.Tipoactividadcongreso = @"N";
            this.Orden = 0;
            this.Codtipoactividad = @"N";
            this.Tarifasactividads = new HashSet<Tarifasactividad>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idtipoactividadcongreso in the schema.
        /// </summary>
        public virtual int Idtipoactividadcongreso
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tipoactividadcongreso in the schema.
        /// </summary>
        public virtual string Tipoactividadcongreso
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Orden in the schema.
        /// </summary>
        public virtual System.Nullable<int> Orden
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Codtipoactividad in the schema.
        /// </summary>
        public virtual string Codtipoactividad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tarifasactividads in the schema.
        /// </summary>
        public virtual ISet<Tarifasactividad> Tarifasactividads
        {
            get;
            set;
        }
    }

}
