//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Tramitacionesserviciosreservas, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Tramitacionesserviciosreservas {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Tramitacionesserviciosreservas constructor in the schema.
        /// </summary>
        public Tramitacionesserviciosreservas()
        {
            this.Idtramitacion = 0;
            this.Fkidservicio = 0;
            this.Linea = 0;
            this.Okalternativa1 = @"N";
            this.Okalternativa2 = @"N";
            this.Okalternativa3 = @"N";
            this.Idestado = @"NULL";
            this.Pvp1 = 0;
            this.Pvp2 = 0;
            this.Pvp3 = 0;
            this.Validez1 = @"N";
            this.Validez2 = @"N";
            this.Validez3 = @"N";
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idtramitacion in the schema.
        /// </summary>
        public virtual int Idtramitacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fkidservicio in the schema.
        /// </summary>
        public virtual int Fkidservicio
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Linea in the schema.
        /// </summary>
        public virtual int Linea
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Requerimientos in the schema.
        /// </summary>
        public virtual string Requerimientos
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Alternativa1 in the schema.
        /// </summary>
        public virtual string Alternativa1
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Okalternativa1 in the schema.
        /// </summary>
        public virtual string Okalternativa1
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Alternativa2 in the schema.
        /// </summary>
        public virtual string Alternativa2
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Okalternativa2 in the schema.
        /// </summary>
        public virtual string Okalternativa2
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Alternativa3 in the schema.
        /// </summary>
        public virtual string Alternativa3
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Okalternativa3 in the schema.
        /// </summary>
        public virtual string Okalternativa3
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idestado in the schema.
        /// </summary>
        public virtual string Idestado
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Pvp1 in the schema.
        /// </summary>
        public virtual System.Nullable<double> Pvp1
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Pvp2 in the schema.
        /// </summary>
        public virtual System.Nullable<double> Pvp2
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Pvp3 in the schema.
        /// </summary>
        public virtual System.Nullable<double> Pvp3
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Requerimientos2 in the schema.
        /// </summary>
        public virtual string Requerimientos2
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idproveedor1 in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idproveedor1
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idproveedor2 in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idproveedor2
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idproveedor3 in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idproveedor3
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idproductoprv1 in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idproductoprv1
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idproductoprv2 in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idproductoprv2
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idproductoprv3 in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idproductoprv3
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Requerimientos3 in the schema.
        /// </summary>
        public virtual string Requerimientos3
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Validez1 in the schema.
        /// </summary>
        public virtual string Validez1
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Validez2 in the schema.
        /// </summary>
        public virtual string Validez2
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Validez3 in the schema.
        /// </summary>
        public virtual string Validez3
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idproveedor4 in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idproveedor4
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idproveedor5 in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idproveedor5
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Idproveedor6 in the schema.
        /// </summary>
        public virtual System.Nullable<int> Idproveedor6
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Gastoscancelacion1 in the schema.
        /// </summary>
        public virtual string Gastoscancelacion1
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Gastoscancelacion2 in the schema.
        /// </summary>
        public virtual string Gastoscancelacion2
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Gastoscancelacion3 in the schema.
        /// </summary>
        public virtual string Gastoscancelacion3
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Serviciosreservasviajes in the schema.
        /// </summary>
        public virtual Serviciosreservasviajes Serviciosreservasviajes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Estadosreservas in the schema.
        /// </summary>
        public virtual Estadosreservas Estadosreservas
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Proveedores_IdProveedor1 in the schema.
        /// </summary>
        public virtual Proveedores Proveedores_IdProveedor1
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Proveedores_IdProveedor2 in the schema.
        /// </summary>
        public virtual Proveedores Proveedores_IdProveedor2
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Proveedores_IdProveedor3 in the schema.
        /// </summary>
        public virtual Proveedores Proveedores_IdProveedor3
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Proveedores_IdProveedor4 in the schema.
        /// </summary>
        public virtual Proveedores Proveedores_IdProveedor4
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Proveedores_IdProveedor5 in the schema.
        /// </summary>
        public virtual Proveedores Proveedores_IdProveedor5
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Proveedores_IdProveedor6 in the schema.
        /// </summary>
        public virtual Proveedores Proveedores_IdProveedor6
        {
            get;
            set;
        }
    }

}
