//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.Tratamientos, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class Tratamientos {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Tratamientos constructor in the schema.
        /// </summary>
        public Tratamientos()
        {
            this.Idtratamiento = 0;
            this.Ttocarta = @"N";
            this.Ttocertificado = @"N";
            this.Ttomsd = @"N";
            this.Locked = 0;
            this.PassengersLists = new HashSet<PassengersList>();
            this.Peticionarios = new HashSet<Peticionarios>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idtratamiento in the schema.
        /// </summary>
        public virtual int Idtratamiento
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Ttocarta in the schema.
        /// </summary>
        public virtual string Ttocarta
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Ttocertificado in the schema.
        /// </summary>
        public virtual string Ttocertificado
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Ttomsd in the schema.
        /// </summary>
        public virtual string Ttomsd
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PassengersLists in the schema.
        /// </summary>
        public virtual ISet<PassengersList> PassengersLists
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Peticionarios in the schema.
        /// </summary>
        public virtual ISet<Peticionarios> Peticionarios
        {
            get;
            set;
        }
    }

}
