//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22/12/2022 11:46:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EOS.ServiceModel
{

    /// <summary>
    /// There are no comments for EOS.ServiceModel.ValoracionFi, EOS.ServiceModel in the schema.
    /// </summary>
    public partial class ValoracionFi {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for ValoracionFi constructor in the schema.
        /// </summary>
        public ValoracionFi()
        {
            this.Idvaloracionfi = 0;
            this.Descripcion = @"N";
            this.Color = 0;
            this.Congresos = new HashSet<Congresos>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Idvaloracionfi in the schema.
        /// </summary>
        public virtual int Idvaloracionfi
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Descripcion in the schema.
        /// </summary>
        public virtual string Descripcion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Color in the schema.
        /// </summary>
        public virtual int Color
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Locked in the schema.
        /// </summary>
        public virtual System.Nullable<int> Locked
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Congresos in the schema.
        /// </summary>
        public virtual ISet<Congresos> Congresos
        {
            get;
            set;
        }
    }

}
