//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenesysImportProcess.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftpserver.quodem.com")]
        public string SftpHost {
            get {
                return ((string)(this["SftpHost"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp_eos")]
        public string SftpUserName {
            get {
                return ((string)(this["SftpUserName"]));
            }
            set {
                this["SftpUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YI3FHafYj2x")]
        public string SftpPassword {
            get {
                return ((string)(this["SftpPassword"]));
            }
            set {
                this["SftpPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public int SftpPort {
            get {
                return ((int)(this["SftpPort"]));
            }
            set {
                this["SftpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/MSD_IN/")]
        public string SftpInitialDirectory {
            get {
                return ((string)(this["SftpInitialDirectory"]));
            }
            set {
                this["SftpInitialDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ItemsPerInsert {
            get {
                return ((int)(this["ItemsPerInsert"]));
            }
            set {
                this["ItemsPerInsert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\t")]
        public string CsvSeparator {
            get {
                return ((string)(this["CsvSeparator"]));
            }
            set {
                this["CsvSeparator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TestMode {
            get {
                return ((bool)(this["TestMode"]));
            }
            set {
                this["TestMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sp_genesys_load_master_table")]
        public string StoreProcedureNameLoadMasterTable {
            get {
                return ((string)(this["StoreProcedureNameLoadMasterTable"]));
            }
            set {
                this["StoreProcedureNameLoadMasterTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MSD Importación de datos de Genesys")]
        public string ProcessDescription {
            get {
                return ((string)(this["ProcessDescription"]));
            }
            set {
                this["ProcessDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\jmartin\\Desktop\\Eos.Genesys\\")]
        public string LocalDirectoryToDownloadPath {
            get {
                return ((string)(this["LocalDirectoryToDownloadPath"]));
            }
            set {
                this["LocalDirectoryToDownloadPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string TxtSeparator {
            get {
                return ((string)(this["TxtSeparator"]));
            }
            set {
                this["TxtSeparator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hcp_genesys_tmp")]
        public string TempTableName {
            get {
                return ((string)(this["TempTableName"]));
            }
            set {
                this["TempTableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\jmartin\\Desktop\\Eos.Genesys\\")]
        public string FileLogDirectory {
            get {
                return ((string)(this["FileLogDirectory"]));
            }
            set {
                this["FileLogDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sp_genesys_update_passengerList")]
        public string StoreProcedureUpdatePassengerList {
            get {
                return ((string)(this["StoreProcedureUpdatePassengerList"]));
            }
            set {
                this["StoreProcedureUpdatePassengerList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DateFormatGenesysFileMasterPattern {
            get {
                return ((string)(this["DateFormatGenesysFileMasterPattern"]));
            }
            set {
                this["DateFormatGenesysFileMasterPattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("agency_prescriber_master.txt")]
        public string GenesysFileMasterPattern {
            get {
                return ((string)(this["GenesysFileMasterPattern"]));
            }
            set {
                this["GenesysFileMasterPattern"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=desarrollo.sqlserver.quodemspain.es;Database=wintour_robot_eos-development" +
            ";User Id=desarrollo;Password=Quowppo10;")]
        public string SqlConnectionString {
            get {
                return ((string)(this["SqlConnectionString"]));
            }
        }
    }
}
