namespace EOS.Web.Enums
{
    public enum EstadosAmec
    {
        Aprobado = 1,
        PendienteDeAprobar = 2,
        Cancelado = 3,
        Rechazado = 4,
        Borrador = 5,
        PendienteDtoMedico = 6,
        PendienteDtoRestoOrganizacion = 7,
        PendienteSupJerarquico = 8,
        PendienteSupJerarquicoRestoOrganizacion = 9,
        PendienteNegocio = 10,
        PendienteNegocioRestoOrganizacion = 11,
        PendienteBUD = 12,
        PendienteBUDRestoOrganizacion = 13,
        PendienteDtoLegal = 14,
        PendienteDtoLRestoOrganizacion = 15,
        PendienteCompliance = 16,
        PendienteComplianceRestoOrganizacion = 17,
        PendienteMD = 18,
        PendienteMDRestoOrganizacion = 19,
        AprobadoDtoMedico = 20,
        AprobadoSupJerarquico = 21,
        AprobadoNegocio = 22,
        AprobadoBUD = 23,
        AprobadoDtoLegal = 24,
        AprobadoCompliance = 25,
        AprobadoMD = 26,
        //PendienteNegocio = 27,
        //AprobadoNegocio = 28,
        AmecSometido = 29,
        AprobadoCondicionadoDtoMedico = 30,
        AprobadoCondicionadoSupJerarquico = 31,
        AprobadoCondicionadoNegocio = 32,
        AprobadoCondicionadoDtoLegal = 34,
        PendienteSometer = 35,
        PreaprobadoDtoMedico = 36,
        PreaprobadoDtoLegal = 37,
        PreaprobadoNegocio = 38,
        PendienteMultiaprobacion = 39,
        AprobadoMultiaprobacion = 40,
        PendienteSupJerarquicoCreador = 41,
        AprobadoSupJerarquicoCreador = 42,
        PendienteNegocioAssistant = 43,
        AprobadoNegocioAssistant = 44,
        PendienteSupJerAssistant = 45,
        AprobadoSupJerAssistant = 46,
    }
}