//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace msd.GenesysCreateReportProcess.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sp_hcp_report_new")]
        public string StoreProcedureDataName {
            get {
                return ((string)(this["StoreProcedureDataName"]));
            }
            set {
                this["StoreProcedureDataName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("quodem@quodem.com")]
        public string EmailFrom {
            get {
                return ((string)(this["EmailFrom"]));
            }
            set {
                this["EmailFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Le enviamos adjunto el reporte del periodo")]
        public string EmailBodyTemplate {
            get {
                return ((string)(this["EmailBodyTemplate"]));
            }
            set {
                this["EmailBodyTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("no-reply")]
        public string EmailSubject {
            get {
                return ((string)(this["EmailSubject"]));
            }
            set {
                this["EmailSubject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sp_hcp_report_time_controller")]
        public string StoreProcedureTimeControllername {
            get {
                return ((string)(this["StoreProcedureTimeControllername"]));
            }
            set {
                this["StoreProcedureTimeControllername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sp_hcp_report_prepare")]
        public string StoreProcedurePrepare {
            get {
                return ((string)(this["StoreProcedurePrepare"]));
            }
            set {
                this["StoreProcedurePrepare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MSD Generación de Informe")]
        public string ProcessDescription {
            get {
                return ((string)(this["ProcessDescription"]));
            }
            set {
                this["ProcessDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Efpia_Report.xlsx")]
        public string FileExportName {
            get {
                return ((string)(this["FileExportName"]));
            }
            set {
                this["FileExportName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\jmartin\\Desktop\\EOSProcess\\")]
        public string FileLogDirectory {
            get {
                return ((string)(this["FileLogDirectory"]));
            }
            set {
                this["FileLogDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\jmartin\\Desktop\\EOSProcess\\")]
        public string FileExportDirectory {
            get {
                return ((string)(this["FileExportDirectory"]));
            }
            set {
                this["FileExportDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jmartin@quodem.com,jmmv80@hotmail.com")]
        public string EmailList {
            get {
                return ((string)(this["EmailList"]));
            }
            set {
                this["EmailList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InstanceNumber {
            get {
                return ((string)(this["InstanceNumber"]));
            }
            set {
                this["InstanceNumber"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=pre-dbserver01.quodem.net;Database=WINTOUR_ROBOT_EOS_UAT-STAGING;User Id=q" +
            "uodem_web;Password=Quowppo10;")]
        public string SqlConnectioString {
            get {
                return ((string)(this["SqlConnectioString"]));
            }
        }
    }
}
