//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Process.BudgetReport.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("quodem@quodem.com")]
        public string EmailFrom {
            get {
                return ((string)(this["EmailFrom"]));
            }
            set {
                this["EmailFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Le enviamos adjunto el reporte del periodo")]
        public string EmailBodyTemplate {
            get {
                return ((string)(this["EmailBodyTemplate"]));
            }
            set {
                this["EmailBodyTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("no-reply")]
        public string EmailSubject {
            get {
                return ((string)(this["EmailSubject"]));
            }
            set {
                this["EmailSubject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\jmartin\\Desktop\\EOSProcess\\")]
        public string FileLogDirectory {
            get {
                return ((string)(this["FileLogDirectory"]));
            }
            set {
                this["FileLogDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\jmartin\\Desktop\\EOSProcess\\")]
        public string FileExportDirectory {
            get {
                return ((string)(this["FileExportDirectory"]));
            }
            set {
                this["FileExportDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jmartin@quodem.com,jmmv80@hotmail.com")]
        public string EmailList {
            get {
                return ((string)(this["EmailList"]));
            }
            set {
                this["EmailList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InstanceNumber {
            get {
                return ((string)(this["InstanceNumber"]));
            }
            set {
                this["InstanceNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sp_budget_report")]
        public string StoreProcedureDataName {
            get {
                return ((string)(this["StoreProcedureDataName"]));
            }
            set {
                this["StoreProcedureDataName"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=PRE-DBServer01.quodem.net;Database=WINTOUR_ROBOT_EOS-STAGING;User Id=quode" +
            "m_web;Password=Quowppo10;")]
        public string SqlConnectioString {
            get {
                return ((string)(this["SqlConnectioString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sp_budget_report_time_controller")]
        public string StoreProcedureTimeControllername {
            get {
                return ((string)(this["StoreProcedureTimeControllername"]));
            }
            set {
                this["StoreProcedureTimeControllername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sp_budget_report_prepare")]
        public string StoreProcedurePrepare {
            get {
                return ((string)(this["StoreProcedurePrepare"]));
            }
            set {
                this["StoreProcedurePrepare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MSD Generación de Informe de Budget")]
        public string ProcessDescription {
            get {
                return ((string)(this["ProcessDescription"]));
            }
            set {
                this["ProcessDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Budget_Report.xlsx")]
        public string FileExportName {
            get {
                return ((string)(this["FileExportName"]));
            }
            set {
                this["FileExportName"] = value;
            }
        }
    }
}
