
namespace EOS.ServiceLogic.Enums
{
    public enum ErrorCode
    {
        [System.ComponentModel.DataAnnotations.Display(Name = "Código de acceso inválido")]
        BadToken = 1,
        [System.ComponentModel.DataAnnotations.Display(Name = "La llave pública no es válida")]
        PublicKeyNotValid = 2,
        [System.ComponentModel.DataAnnotations.Display(Name = "Usuario no encontrado")]
        UserNotFound = 3,
        [System.ComponentModel.DataAnnotations.Display(Name = "Credenciales no válidas")]
        CredentialsNotValid = 4,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error salvando al usuario")]
        ErrorSavingUser = 5,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error creando el lote")]
        ErrorCreatingLot = 6,
        [System.ComponentModel.DataAnnotations.Display(Name = "Datos del lote no válidos")]
        LotDataNotValid = 7,
        [System.ComponentModel.DataAnnotations.Display(Name = "Lote no encontrado")]
        LotNotFound = 8,
        [System.ComponentModel.DataAnnotations.Display(Name = "El lote ya ha sido asignado")]
        LotAlreadyAssigned = 9,
        [System.ComponentModel.DataAnnotations.Display(Name = "El salvando el lote")]
        ErrorSavingLot = 10,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error generando el código de acceso")]
        ErrorGettingAccessToken = 11,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error validando el usuario")]
        UserValidationError = 12,
        [System.ComponentModel.DataAnnotations.Display(Name = "Email no válido")]
        EmailNotValid = 13,
        [System.ComponentModel.DataAnnotations.Display(Name = "No se ha encontrado un curso")]
        CourseNotFound = 14,
        [System.ComponentModel.DataAnnotations.Display(Name = "El curso no ha sido salvado")]
        CourseNotSaved = 15,
        [System.ComponentModel.DataAnnotations.Display(Name = "Parámetros insuficientes")]
        InsuficientParams = 16,
        [System.ComponentModel.DataAnnotations.Display(Name = "El curso no es válido")]
        CourseNotValid = 17,
        [System.ComponentModel.DataAnnotations.Display(Name = "El filtro no puede ser nulo")]
        NullFilter = 18,
        [System.ComponentModel.DataAnnotations.Display(Name = "Datos de los cursos no válidos")]
        CourseDataNotValid = 19,
        [System.ComponentModel.DataAnnotations.Display(Name = "Los datos no pueden ser nulos")]
        NullData = 20,
        [System.ComponentModel.DataAnnotations.Display(Name = "El texto no puede ser nulo")]
        NullText = 21,
        [System.ComponentModel.DataAnnotations.Display(Name = "La clave no puede ser nula")]
        NullKey = 22,
        [System.ComponentModel.DataAnnotations.Display(Name = "El usuario no está asignado al curso especificado")]
        UserNotAssigned = 23,
        [System.ComponentModel.DataAnnotations.Display(Name = "Datos no válidos")]
        DataNotValid = 24,
        [System.ComponentModel.DataAnnotations.Display(Name = "Los módulos indicados ya habían sido asignados")]
        ModulesAlreadyAssigned = 25,
        [System.ComponentModel.DataAnnotations.Display(Name = "Uno de los módulos indicados no corresponde al curso")]
        WrongModule = 26,
        [System.ComponentModel.DataAnnotations.Display(Name = "El curso indicado no existe")]
        WrongCourse = 27,
        [System.ComponentModel.DataAnnotations.Display(Name = "El usuario no está asignado a alguno de los módulos especificados")]
        UserNotAssignedToModules = 28,
        [System.ComponentModel.DataAnnotations.Display(Name = "El Login es obligatorio")]
        MandatoryLogin = 29,
        [System.ComponentModel.DataAnnotations.Display(Name = "Datos de entrada no válidos")]
        DataEnterNotValid = 30,
        [System.ComponentModel.DataAnnotations.Display(Name = "Tiene que indicar algún módulo para la asignación ")]
        NoSelectedModule = 31,
        [System.ComponentModel.DataAnnotations.Display(Name = "Problemas en el sistema al gestionar el consentimiento")]
        ConsentProblems = 32,
        [System.ComponentModel.DataAnnotations.Display(Name = "El login y la indicación de consentimiento son obligatorios")]
        ConsentMandatoyData = 33,
        [System.ComponentModel.DataAnnotations.Display(Name = "El número de página tiene que ser mayor que cero")]
        PageError = 34,
        [System.ComponentModel.DataAnnotations.Display(Name = "El formato para las fechas debe ser AAAAMMDD")]
        DateFormatError = 35,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error inesperado")]
        UnexpectedError = 36,
        [System.ComponentModel.DataAnnotations.Display(Name = "La fecha de inicio no puede ser posterior a la fecha de fin")]
        DateFromBiggerThanDateTo = 37,
        [System.ComponentModel.DataAnnotations.Display(Name = "Clave de Agencia inválida.")]
        BadAgencyKey = 38,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de ActividadesPassengerList.")]
        ActividadesPassengerListInsertUpdateError = 39,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de EmpleadosGp.")]
        EmpleadosGpInsertUpdateError = 40,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de EstadosReservas.")]
        EstadosReservasInsertUpdateError = 41,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de Amec.")]
        AmecInsertUpdateError = 42,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de HotelPassengerList.")]
        HotelPassengerListInsertUpdateError = 43,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de InscripcionPassengersList.")]
        InscripcionPassengersListInsertUpdateError = 44,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de Transportepassengerslist.")]
        TransportepassengerslistInsertUpdateError = 44,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de TipoBono.")]
        TipoBonoInsertUpdateError = 45,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de Servicios.")]
        ServiciosInsertUpdateError = 46,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de NivelesAprobacion.")]
        NivelesAprobacionUpdateError = 47,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de Gestorinvitados.")]
        GestorinvitadosInsertUpdateError = 48,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de ReservaViajes.")]
        ReservaViajesInsertUpdateError = 49,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de ReservasPassengersList.")]
        ReservasPassengersListInsertUpdateError = 50,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de Tarifasaloj.")]
        TarifasAlojInsertUpdateError = 51,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de PeticionActividad.")]
        PeticionActividadInsertUpdateError = 52,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de ServiciosReservasActividades.")]
        ServiciosReservasActividadesInsertUpdateError = 53,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de Congresos.")]
        CongresosInsertUpdateError = 54,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de Poblaciones.")]
        PoblacionInsertUpdateError = 55,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de Producto.")]
        ProductosInsertUpdateError = 56,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de ServiciosReservasHotel.")]
        ServiciosReservasHotelInsertUpdateError = 57,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de Expediente.")]
        ExpedienteInsertUpdateError = 58,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de Iatas.")]
        IatasInsertUpdateError = 59,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de ProductosPRV.")]
        ProductosPRVInsertUpdateError = 60,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de Proveedor.")]
        ProveedorInsertUpdateError = 61,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de Provincias.")]
        ProvinciaInsertUpdateError = 62,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de PeticionGrupos.")]
        PeticionGruposInsertUpdateError = 63,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de ServiciosReservasTransporte.")]
        ServiciosReservasTransporteInsertUpdateError = 64,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de ServiciosReservasInscripcion.")]
        ServiciosReservasInscripcionInsertUpdateError = 65,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de Estados_Reservas.")]
        Estados_ReservasInsertUpdateError = 66,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de TarifasInscripcion.")]
        TarifasInscripcionInsertUpdateError = 67,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de TiposPRV.")]
        TiposPRVInsertUpdateError = 68,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de Tiposaloj.")]
        TiposAlojInsertUpdateError = 69,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de TramitacionesServiciosReservas.")]
        TramitacionesServiciosReservasInsertUpdateError = 70,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de TarifasActividad.")]
        TarifasActividadInsertUpdateError = 71,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de ServiciosReservasViajes.")]
        ServiciosReservasViajesInsertUpdateError = 72,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error insertando la versión del documento")]
        GestorDocumentalFirstversion = 73,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error borrando la versión del documento")]
        GestorDocumentalDeleteError = 74,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error edición versión del documento")]
        GestorDocumentalEditorError = 75,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error edición versión del documento. El expediente no tiene relación con el amec.")]
        GestorDocumentalAmecExpedienteError = 76,
        [System.ComponentModel.DataAnnotations.Display(Name = "El Tipo de documento no corresponde a la lista de tipos posibles para el tipo de Expediente")]
        GestorDocumentalTipoDocumentoError = 77,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error edición versión del documento. Se esta intentando insertar una nueva version de un documento que no existe.")]
        GestorDocumentalVersionAnteriorNoExistsError = 78,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error edición versión del documento. El amec que se ha especificado no pertenece a la agencia que envía el documento.")]
        GestorDocumentalAmecAgenciaError = 79,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error durante la inserción o actualización de PeticionariosEmpleadosGp.")]
        PeticionariosEmpleadosGpInsertUpdateError = 80,
        [System.ComponentModel.DataAnnotations.Display(Name = "El ContentType especificado no es válido.")]
        ContentTypeError = 81,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error generando la hora")]
        ErrorGettingDateTime = 82,
        [System.ComponentModel.DataAnnotations.Display(Name = "Error al guardar el fichero en el servidor, ruta demasiado larga.")]
        ErrorDocumentalRutaFichero = 83

    }
}